import { test } from 'node:test';
import assert from 'node:assert/strict';
import { randomBytes } from 'node:crypto';
import { createDatabase } from '../src/db.js';
import { buildApp } from '../src/app.js';
import { sha256 } from '../src/security.js';
import { emptyAIBehaviorPolicy, type AIBehaviorPreviewContext } from '../src/ai/behavior-policy.js';
const url = process.env.TEST_DATABASE_URL; if (!url || new URL(url).pathname !== '/lead_operations_test') throw new Error('Isolated TEST_DATABASE_URL required');
test('AI behavior policy enforces native current scope/version/session/history/Audit, isolated inheritance and write-free returning/handoff/disclosure decisions without activation', async t => {
  process.env.APP_ORIGIN = 'http://127.0.0.1:5173'; const db = createDatabase(url), app = await buildApp(db, { logger: false, globalRateLimitMax: 10000 }); t.after(async () => { await app.close(); await db.end(); });
  await db.begin(async tx => { await tx`SET LOCAL client_min_messages TO warning`; await tx`TRUNCATE background_job CASCADE`; await tx`TRUNCATE organization CASCADE`; });
  const org = (await db`INSERT INTO organization(name) VALUES ('Behavior policy') RETURNING id`)[0]!.id, foreignOrg = (await db`INSERT INTO organization(name) VALUES ('Foreign') RETURNING id`)[0]!.id;
  const branch = (await db`INSERT INTO branch(organization_id,name) VALUES (${org},'A') RETURNING id`)[0]!.id, otherBranch = (await db`INSERT INTO branch(organization_id,name) VALUES (${org},'B') RETURNING id`)[0]!.id;
  const campaign = (await db`INSERT INTO campaign(organization_id,branch_id,name) VALUES (${org},${branch},'A') RETURNING id`)[0]!.id, campaignB = (await db`INSERT INTO campaign(organization_id,branch_id,name) VALUES (${org},${branch},'B') RETURNING id`)[0]!.id;
  const users: Record<string, { id: string; session: string; cookie: string }> = {};
  for (const [name, role, b, o] of [['manager', 'MANAGER', branch, org], ['agent', 'AGENT', branch, org], ['other', 'MANAGER', otherBranch, org], ['admin', 'SUPER_ADMIN', null, org], ['foreign', 'SUPER_ADMIN', null, foreignOrg]] as const) {
    const id = (await db`INSERT INTO user_account(organization_id,branch_id,role,name,email,password_hash) VALUES (${o},${b},${role},${name},${name + '@behavior.test'},'synthetic-only') RETURNING id`)[0]!.id, token = randomBytes(32).toString('hex');
    const session = (await db`INSERT INTO user_session(user_id,token_hash,created_at,expires_at) VALUES (${id},${sha256(token)},now()-interval '1 hour',now()+interval '1 hour') RETURNING id`)[0]!.id; users[name] = { id, session, cookie: 'lop_session=' + token };
  }
  const root = '/api/ai/campaigns/' + campaign + '/behavior-policy', defaults = '/api/ai/branches/' + branch + '/behavior-defaults', effective = '/api/ai/campaigns/' + campaign + '/effective-configuration';
  const api = (method: 'GET' | 'PUT' | 'POST', path: string, payload?: object, actor = 'manager') => app.inject({ method, url: path, payload, headers: { origin: process.env.APP_ORIGIN!, cookie: users[actor]!.cookie } });
  const def = { ...emptyAIBehaviorPolicy(), formality: 'Approved formal language', disclosure: { mode: 'FIRST_AI_MESSAGE' as const, text: 'I am your AI assistant <img literal>.' }, handoff: { initialContactWithoutAgent: true, transitionMessage: 'The team will follow up.', misunderstandingLimit: 3 } }, body = { version: 0, definition: def, reason: 'Configure explicit behavior defaults' };
  assert.equal((await api('GET', root)).json().version, 0); const initial = (await api('GET', effective)).json(); assert.ok(initial.blockers.includes('AI_DISCLOSURE_POLICY_REQUIRED'));
  for (const actor of ['agent', 'other', 'foreign']) for (const path of [root, defaults, root + '/history', root + '/versions/1', effective]) assert.equal((await api('GET', path, undefined, actor)).statusCode, actor === 'agent' ? 403 : 404);
  for (const invalid of [{ ...def, disclosure: { mode: 'HIDE_AI', text: 'Hidden' } }, { ...def, handoff: { ...def.handoff, stopOnUnknown: false } }, { ...def, formality: '\u0000' }, { ...def, formality: '\ud800' }]) {
    assert.equal((await api('PUT', defaults, { ...body, definition: invalid })).statusCode, 400);
    if (!JSON.stringify(invalid).includes('\\u0000') && !JSON.stringify(invalid).includes('\\ud800')) assert.equal((await db`SELECT ai_behavior_policy_valid(${db.json(invalid)}) AS valid`)[0]!.valid, false);
  }
  const raced = await Promise.all(Array.from({ length: 4 }, () => api('PUT', defaults, body))); assert.deepEqual(raced.map(r => r.statusCode).sort(), [200, 409, 409, 409]);
  const inherited = (await api('GET', effective)).json(); assert.notEqual(inherited.hash, initial.hash); assert.equal(inherited.behavior.branchVersion, 1); assert.equal(inherited.behavior.sources.disclosure, 'BRANCH'); assert.equal(inherited.behavior.sources.returningContact, 'UNCONFIGURED'); assert.equal(inherited.assistantReady, false); assert.deepEqual(inherited.allowedTools, []);
  assert.equal((await api('PUT', defaults, { ...body, version: 1, definition: { ...def, returningContact: { closedConversation: 'REOPEN_EXISTING', closedLead: 'CREATE_NEW' } } })).statusCode, 400);
  await assert.rejects(db`UPDATE ai_behavior_policy SET version=version+1,definition=${db.json({ ...def, returningContact: { closedConversation: 'REVIEW', closedLead: 'REVIEW' } })} WHERE scope='BRANCH' AND resource_id=${branch}`, /AI_BEHAVIOR_INVALID/);
  const override = { ...emptyAIBehaviorPolicy(), formality: '', returningContact: { closedConversation: 'REOPEN_EXISTING' as const, closedLead: 'CREATE_NEW' as const } };
  assert.equal((await api('PUT', root, { version: 0, definition: override, reason: 'Explicit current Campaign returning rule' })).statusCode, 200);
  const changed = (await api('GET', effective)).json(); assert.equal(changed.behavior.effective.formality, ''); assert.equal(changed.behavior.sources.formality, 'CAMPAIGN'); assert.equal(changed.behavior.effective.returningContact.closedLead, 'CREATE_NEW'); assert.equal((await api('GET', '/api/ai/campaigns/' + campaignB + '/effective-configuration')).json().behavior.effective.returningContact, null); assert.equal((await api('GET', effective)).json().hash, changed.hash);
  const context: AIBehaviorPreviewContext = { leadLifecycle: 'OPEN', controllerType: 'AI', conversationState: 'AI_ACTIVE', resolution: 'UNIQUE', explicitCampaignReference: false, requiredLeadData: false, disclosureAlreadySent: false, humanAvailable: false, trigger: 'UNKNOWN_ANSWER', misunderstandingCount: 0, qualificationHandoffRequired: false };
  const preview = { branchVersion: 1, campaignVersion: 1, context }, view = await api('POST', root + '/preview', preview); assert.equal(view.statusCode, 200, view.body); assert.equal(view.json().handoff.action, 'WAITING_FOR_HUMAN'); assert.equal(view.json().handoff.notifyManager, true); assert.equal(view.json().disclosure, def.disclosure.text); assert.equal(view.json().sendAllowed, false); assert.equal(view.json().mutationsAllowed, false);
  const outcome = async (delta: object) => (await api('POST', root + '/preview', { ...preview, context: { ...context, ...delta } })).json();
  assert.equal((await outcome({ trigger: 'CUSTOMER_REQUEST', humanAvailable: true })).handoff.action, 'REQUEST_HANDOFF'); assert.equal((await outcome({ controllerType: 'HUMAN', conversationState: 'HUMAN_ACTIVE' })).returning.action, 'HUMAN');
  assert.equal((await outcome({ conversationState: 'WAITING_FOR_HUMAN' })).returning.action, 'HUMAN_REVIEW'); assert.equal((await outcome({ conversationState: 'CLOSED' })).returning.action, 'REOPEN_EXISTING');
  assert.equal((await outcome({ leadLifecycle: 'CLOSED' })).returning.action, 'REVIEW'); assert.equal((await outcome({ leadLifecycle: 'CLOSED', explicitCampaignReference: true, requiredLeadData: true })).returning.action, 'CREATE_NEW');
  for (const delta of [{ resolution: 'AMBIGUOUS' }, { resolution: 'UNRESOLVED' }, { leadLifecycle: 'ARCHIVED', explicitCampaignReference: true, requiredLeadData: true }]) assert.equal((await outcome(delta)).returning.action, 'REVIEW');
  assert.equal((await outcome({ disclosureAlreadySent: true })).disclosure, null); assert.equal((await api('POST', root + '/preview', { ...preview, branchVersion: 0 })).statusCode, 409); assert.equal((await api('POST', root + '/preview', { ...preview, context: { ...context, tool: 'MARK_PAID' } })).statusCode, 400); assert.equal((await api('POST', root + '/preview', preview, 'agent')).statusCode, 403);
  for (const table of ['lead', 'conversation', 'conversation_message', 'background_job'] as const) assert.equal((await db`SELECT count(*)::integer AS n FROM ${db(table)}`)[0]!.n, 0);
  await assert.rejects(db`UPDATE ai_behavior_policy SET version=version+2 WHERE scope='CAMPAIGN' AND resource_id=${campaign}`, /VERSION_REQUIRED/); await assert.rejects(db`DELETE FROM ai_behavior_policy WHERE scope='CAMPAIGN' AND resource_id=${campaign}`, /HISTORY_RETAINED/); await assert.rejects(db`UPDATE ai_behavior_policy_history SET snapshot='{}' WHERE resource_id=${campaign}`, /HISTORY_IMMUTABLE/);
  await assert.rejects(db`UPDATE ai_behavior_policy SET version=version+1,actor_id=${users.agent!.id},session_id=${users.agent!.session} WHERE scope='CAMPAIGN' AND resource_id=${campaign}`, /CURRENT_ACCESS_REQUIRED/);
  await db`UPDATE user_session SET revoked_at=clock_timestamp() WHERE id=${users.manager!.session}`; await assert.rejects(db`UPDATE ai_behavior_policy SET version=version+1 WHERE scope='CAMPAIGN' AND resource_id=${campaign}`, /CURRENT_ACCESS_REQUIRED/); assert.equal((await api('GET', root)).statusCode, 401); await db`UPDATE user_session SET revoked_at=NULL WHERE id=${users.manager!.session}`;
  await db`UPDATE user_session SET expires_at=clock_timestamp()-interval '1 second' WHERE id=${users.manager!.session}`; await assert.rejects(db`UPDATE ai_behavior_policy SET version=version+1 WHERE scope='CAMPAIGN' AND resource_id=${campaign}`, /CURRENT_ACCESS_REQUIRED/); await db`UPDATE user_session SET expires_at=clock_timestamp()+interval '1 hour' WHERE id=${users.manager!.session}`;
  await db`CREATE FUNCTION synthetic_behavior_audit_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.action='AI_BEHAVIOR_POLICY_CONFIGURED' THEN RAISE EXCEPTION 'synthetic audit failure';END IF;RETURN NEW;END $$`; await db`CREATE TRIGGER synthetic_behavior_audit BEFORE INSERT ON audit_log FOR EACH ROW EXECUTE FUNCTION synthetic_behavior_audit_failure()`;
  try { assert.equal((await api('PUT', root, { version: 1, definition: emptyAIBehaviorPolicy(), reason: 'Audit rollback must be atomic' })).statusCode, 500); assert.equal((await api('GET', root)).json().version, 1); assert.equal((await api('GET', root + '/history')).json().items.length, 1); }
  finally { await db`DROP TRIGGER synthetic_behavior_audit ON audit_log`; await db`DROP FUNCTION synthetic_behavior_audit_failure()`; }
  const edits = await Promise.all(Array.from({ length: 4 }, () => api('PUT', root, { version: 1, definition: emptyAIBehaviorPolicy(), reason: 'Explicit clear overrides retains history' }))); assert.deepEqual(edits.map(r => r.statusCode).sort(), [200, 409, 409, 409]);
  assert.deepEqual((await api('GET', root + '/versions/1')).json().definition, override); assert.equal((await api('GET', root + '/history?limit=1')).json().nextVersion, 2); assert.equal((await api('GET', root + '/history?before=2')).json().items[0].version, 1); assert.equal((await api('GET', effective)).json().behavior.sources.formality, 'BRANCH');
  await db`UPDATE branch SET active=false WHERE id=${branch}`; assert.equal((await api('PUT', root, { version: 2, definition: override, reason: 'Disabled Branch denied' })).statusCode, 409); assert.equal((await api('GET', root + '/versions/1')).statusCode, 200); await assert.rejects(db`UPDATE ai_behavior_policy SET version=version+1 WHERE scope='CAMPAIGN' AND resource_id=${campaign}`, /CURRENT_ACCESS_REQUIRED/);
});
