import test from 'node:test';
import assert from 'node:assert/strict';
import { randomBytes } from 'node:crypto';
import { buildApp } from '../src/app.js';
import { createDatabase } from '../src/db.js';
import { sha256 } from '../src/security.js';
const url=process.env.TEST_DATABASE_URL;if(!url || new URL(url).pathname!=='/lead_operations_test')throw new Error('Isolated TEST_DATABASE_URL required');
test('AI managed connections/profiles enforce current scope/session/catalog/version, encrypted rotation, late-response fences and audit/history atomicity',async(t)=> {
  process.env.APP_ORIGIN='http://127.0.0.1:5173';process.env.CREDENTIAL_ENCRYPTION_KEY=randomBytes(32).toString('hex');
  const db=createDatabase(url),app=await buildApp(db,{ logger:false,globalRateLimitMax:10000 });t.after(async()=>{ await app.close();await db.end(); });
  const oldFetch=globalThis.fetch;t.after(()=>{ globalThis.fetch=oldFetch; });let calls=0,fail=false,hold:Promise<void>|null=null;let called!:()=>void;
  globalThis.fetch=async(input,init)=> { assert.equal(input,'https://api.openai.com/v1/models');assert.equal(init?.method,'GET');assert.equal(init?.body,undefined);calls++;called?.();if(hold)await hold;
    if(fail)return new Response('synthetic private credential error',{ status:401 });
    return new Response(JSON.stringify({ object:'list',data:[{ id:'Synthetic-model-a',object:'model',owned_by:'Private synthetic metadata' },{ id:'Synthetic-model-b',object:'model' }] })); };
  await db.begin(async(tx)=>{ await tx`SET LOCAL client_min_messages TO warning`;await tx`TRUNCATE background_job CASCADE`;await tx`TRUNCATE organization CASCADE`; });
  const org=(await db`INSERT INTO organization(name) VALUES ('AI tests') RETURNING id`)[0]!.id;
  const foreignOrg=(await db`INSERT INTO organization(name) VALUES ('Foreign AI') RETURNING id`)[0]!.id;
  const branch=(await db`INSERT INTO branch(organization_id,name) VALUES (${org},'A') RETURNING id`)[0]!.id;
  const branchB=(await db`INSERT INTO branch(organization_id,name) VALUES (${org},'B') RETURNING id`)[0]!.id;
  const users:Record<string,{ id:string;cookie:string;session:string }>={};
  for(const [name,role,b,o] of [['manager','MANAGER',branch,org],['other','MANAGER',branchB,org],['agent','AGENT',branch,org],['admin','SUPER_ADMIN',null,org],['foreign','SUPER_ADMIN',null,foreignOrg]] as const) {
    const id=(await db`INSERT INTO user_account(organization_id,branch_id,name,role,email,password_hash) VALUES (${o},${b},${name},${role},${name+'@ai.test'},'synthetic-only') RETURNING id`)[0]!.id;
    const token=randomBytes(32).toString('hex');const session=(await db`INSERT INTO user_session(user_id,token_hash,created_at,expires_at) VALUES (${id},${sha256(token)},now()-interval '1 hour',now()+interval '1 hour') RETURNING id`)[0]!.id;users[name]={ id,session,cookie:'lop_session='+token };
  }
  const api=(method:'GET'|'POST'|'PUT',path:string,payload?:object,actor='manager')=>app.inject({ method,url:path,payload,headers:{ origin:process.env.APP_ORIGIN!,cookie:users[actor]!.cookie } });
  const key='SyntheticAISecret_123456789';const input={ name:'Connection <img literal>',branchId:branch,provider:'OPENAI',credential:key,reason:'Synthetic AI setup' };
  assert.equal((await api('POST','/api/ai/connections',input,'agent')).statusCode,403);assert.equal((await api('POST','/api/ai/connections',{ ...input,branchId:branchB })).statusCode,403);
  assert.equal((await api('POST','/api/ai/connections',{ ...input,branchId:null })).statusCode,403);
  const created=await api('POST','/api/ai/connections',input);assert.equal(created.statusCode,201,created.body);const id=created.json().id,root='/api/ai/connections/'+id;
  const sealed=(await db`SELECT ciphertext FROM connection_secret WHERE connection_id=${id}`)[0]!;assert.equal(sealed.ciphertext.toString().includes(key),false);
  const shared=await api('POST','/api/ai/connections',{ ...input,branchId:null,name:'Shared AI' },'admin');assert.equal(shared.statusCode,201);
  assert.equal((await api('GET','/api/ai/connections',undefined,'other')).json().items.length,0);assert.equal((await api('GET','/api/ai/connections',undefined,'foreign')).json().items.length,0);
  assert.equal((await api('GET',root+'/history',undefined,'agent')).statusCode,403);assert.equal((await api('GET',root+'/history',undefined,'other')).statusCode,404);
  const profileInput={ connectionId:id,name:'Conversation profile',task:'CONVERSATION',modelId:'Synthetic-model-a',maxOutputTokens:1024,active:true,reason:'Use a configured model' };
  assert.equal((await api('POST','/api/ai/profiles',profileInput)).statusCode,409);
  const verification=await api('POST',root+'/test',{ version:1 });assert.equal(verification.statusCode,200,verification.body);assert.equal(verification.json().state,'VERIFIED');assert.equal(verification.json().inferenceVerified,false);
  const listed=(await api('GET','/api/ai/connections')).json();assert.equal(listed.items[0].capabilities.models,undefined);assert.equal(listed.items[0].capabilities.modelCount,2);assert.equal(JSON.stringify(listed).includes(key),false);assert.equal(JSON.stringify(listed).includes('Private synthetic metadata'),false);
  const modelPage=(await api('GET',root+'/models?limit=1')).json();assert.equal(modelPage.items.length,1);assert.ok(modelPage.nextAfter);
  assert.deepEqual((await api('GET',root+'/models?after='+encodeURIComponent(modelPage.nextAfter))).json().items,['Synthetic-model-b']);
  const profile=await api('POST','/api/ai/profiles',profileInput);assert.equal(profile.statusCode,201,profile.body);const profileId=profile.json().id;
  assert.equal((await api('POST','/api/ai/profiles',{ ...profileInput,modelId:'not-in-catalog' })).statusCode,409);
  assert.equal((await api('POST','/api/ai/profiles',profileInput,'agent')).statusCode,403);assert.equal((await api('POST','/api/ai/profiles',profileInput,'other')).statusCode,404);
  const profilePath='/api/ai/profiles/'+profileId;
  const edits=await Promise.all([api('PUT',profilePath,{ ...profileInput,version:1,name:'Changed profile one' }),api('PUT',profilePath,{ ...profileInput,version:1,name:'Changed profile two' })]);assert.deepEqual(edits.map((x)=>x.statusCode).sort(),[200,409]);
  assert.equal((await api('GET',profilePath+'/history?limit=1')).json().nextVersion,2);assert.equal((await api('GET',profilePath+'/history?before=2')).json().items[0].snapshot.name,'Conversation profile');
  await assert.rejects(()=>db`UPDATE ai_profile_history SET snapshot='{}' WHERE profile_id=${profileId}`,/AI_PROFILE_HISTORY_IMMUTABLE/);
  await assert.rejects(()=>db`DELETE FROM ai_model_profile WHERE id=${profileId}`,/AI_PROFILE_HISTORY_RETAINED/);
  await assert.rejects(()=>db`UPDATE integration_connection SET branch_id=${branchB} WHERE id=${id}`,/AI_CONNECTION_IDENTITY_IMMUTABLE/);
  let release!:()=>void;hold=new Promise<void>((r)=>release=r);const entered=new Promise<void>((r)=>called=r);
  const running=api('POST',root+'/test',{ version:1 });await entered;
  assert.equal((await api('POST',root+'/test',{ version:1 })).statusCode,409);
  const rotated=await api('PUT',root,{ name:'Rotated AI',credential:'SyntheticRotatedCredential_123',version:1,reason:'Rotate synthetic credential' });assert.equal(rotated.statusCode,200);
  release();hold=null;const late=await running;assert.equal(late.json().state,'SUPERSEDED');assert.equal((await api('GET','/api/ai/connections')).json().items[0].status,'NOT_CONFIGURED');
  assert.equal((await api('GET','/api/ai/profiles')).json().items[0].catalog_available,false);
  fail=true;assert.equal((await api('POST',root+'/test',{ version:2 })).json().state,'FAILED');assert.equal((await api('GET','/api/ai/connections')).json().items[0].last_error_code,'AI_AUTH_FAILED');
  fail=false;assert.equal((await api('POST',root+'/test',{ version:2 })).json().state,'VERIFIED');
  hold=new Promise<void>((r)=>release=r);const entered2=new Promise<void>((r)=>called=r);const revoked=api('POST',root+'/test',{ version:2 });await entered2;
  await db`UPDATE user_session SET revoked_at=clock_timestamp() WHERE id=${users.manager!.session}`;release();hold=null;assert.equal((await revoked).statusCode,403);
  await db`UPDATE user_session SET revoked_at=NULL WHERE id=${users.manager!.session}`;
  assert.equal((await api('GET',root+'/probes')).json().items[0].state,'SUPERSEDED');
  await db`CREATE FUNCTION synthetic_ai_profile_audit_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.action='AI_PROFILE_CONFIGURED' THEN RAISE EXCEPTION 'synthetic audit rollback'; END IF;RETURN NEW;END $$`;
  await db`CREATE TRIGGER synthetic_ai_profile_audit BEFORE INSERT ON audit_log FOR EACH ROW EXECUTE FUNCTION synthetic_ai_profile_audit_failure()`;
  try { assert.equal((await api('PUT',profilePath,{ ...profileInput,version:2 })).statusCode,500);assert.equal((await api('GET',profilePath+'/history')).json().items.length,2); }
  finally { await db`DROP TRIGGER synthetic_ai_profile_audit ON audit_log`;await db`DROP FUNCTION synthetic_ai_profile_audit_failure()`; }
  assert.equal((await api('POST',root+'/disable',{ version:2,reason:'Disable AI connection' })).statusCode,200);
  assert.equal((await api('POST',root+'/test',{ version:3 })).statusCode,409);assert.equal((await api('GET','/api/ai/profiles')).json().items[0].catalog_available,false);
  assert.equal((await api('PUT',profilePath,{ ...profileInput,active:false,version:2 })).statusCode,200);
  assert.equal((await api('POST',root+'/reconnect',{ version:3,reason:'Restore AI setup' })).statusCode,200);assert.equal((await api('POST',root+'/test',{ version:4 })).json().state,'VERIFIED');
  const history=(await api('GET',root+'/history?limit=1')).json();assert.ok(history.nextCursor);assert.equal((await api('GET',root+'/history?cursor='+encodeURIComponent(history.nextCursor))).json().items[0].version,3);
  assert.ok(calls>=6);assert.equal(JSON.stringify((await db`SELECT detail FROM audit_log WHERE action LIKE 'AI_%'`)).includes(key),false);
  await db`UPDATE branch SET active=false WHERE id=${branch}`;assert.equal((await api('POST',root+'/test',{ version:4 })).statusCode,409);
  assert.equal((await api('GET',root+'/models')).json().current,false);assert.equal((await api('GET','/api/ai/profiles')).json().items[0].catalog_available,false);
});
