import { test, expect, type Page } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { randomUUID } from 'node:crypto';
test('AI behavior policies configure scoped disclosure/handoff and explicit returning rules, preview safe current decisions and preserve original Browser history', async ({ browser }) => {
  const fixture = JSON.parse(await readFile(resolve('.local/e2e/fixture.json'), 'utf8')) as { password: string };
  const context = await browser.newContext({ extraHTTPHeaders: { 'x-e2e-rate-scope': randomUUID() } }), agentContext = await browser.newContext({ extraHTTPHeaders: { 'x-e2e-rate-scope': randomUUID() } }), page = await context.newPage(), agent = await agentContext.newPage(), errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message)); page.on('console', m => { if (m.type() === 'error' && /same key|unique.*key/i.test(m.text())) errors.push(m.text()); }); const origin = 'http://127.0.0.1:4100';
  const login = async (p: Page, name: string) => { await p.goto('/'); await p.getByRole('combobox', { name: 'Language' }).selectOption('en'); await p.getByLabel('Email', { exact: true }).fill(name + '@browser.test'); await p.getByLabel('Password', { exact: true }).fill(fixture.password); await p.getByRole('button', { name: 'Sign in', exact: true }).click(); await expect(p.getByRole('button', { name: 'Sign out', exact: true })).toBeVisible(); };
  try {
    await login(page, 'manager'); const manager = await (await page.request.get('/api/auth/me')).json();
    const made = await page.request.post('/api/campaigns', { headers: { origin }, data: { name: 'Browser AI Behavior Policy', branchId: manager.branchId, routingMethod: 'MANUAL' } }); expect(made.status()).toBe(201); const c = await made.json(), root = '/api/ai/campaigns/' + c.id + '/behavior-policy', defaults = '/api/ai/branches/' + manager.branchId + '/behavior-defaults';
    const branchBefore = await (await page.request.get(defaults)).json();
    let release!: () => void; const delayedLoad = new Promise<void>(resolve => { release = resolve; }); await page.route('**' + root, async route => { if (route.request().method() === 'GET') await delayedLoad; await route.continue(); });
    await page.getByRole('button', { name: 'Campaigns', exact: true }).click(); await page.getByRole('button', { name: 'Retry', exact: true }).click(); await page.getByRole('row').filter({ hasText: 'Browser AI Behavior Policy' }).getByRole('button', { name: 'Details', exact: true }).click();
    const panel = page.locator('[data-campaign-ai-behavior]'), branch = panel.locator('[data-ai-behavior-scope="BRANCH"]'), campaign = panel.locator('[data-ai-behavior-scope="CAMPAIGN"]');
    await expect(campaign.getByRole('button', { name: 'Save AI behavior', exact: true })).toBeDisabled(); release();
    const label = (scope: 'Branch AI behavior defaults' | 'Campaign AI behavior', field: string) => scope + ' · ' + field;
    await branch.getByLabel(label('Branch AI behavior defaults', 'Configure explicitly AI identity disclosure'), { exact: true }).check(); await branch.getByLabel(label('Branch AI behavior defaults', 'Approved disclosure text'), { exact: true }).fill('I am the AI assistant. <img literal>');
    await branch.getByLabel(label('Branch AI behavior defaults', 'Configure explicitly Human handoff policy'), { exact: true }).check(); await branch.getByLabel(label('Branch AI behavior defaults', 'Approved transition message (optional)'), { exact: true }).fill('Our team will follow up.'); await branch.getByLabel(label('Branch AI behavior defaults', 'Misunderstanding count before handoff (optional)'), { exact: true }).fill('3');
    await branch.getByLabel(label('Branch AI behavior defaults', 'AI behavior edit reason'), { exact: true }).fill('Approved operational disclosure and handoff'); await branch.getByRole('button', { name: 'Save AI behavior', exact: true }).click(); await expect(branch).toContainText('Version: ' + (branchBefore.version + 1));
    await campaign.getByLabel(label('Campaign AI behavior', 'Configure explicitly Formality guidance'), { exact: true }).check(); await campaign.getByLabel(label('Campaign AI behavior', 'Formality guidance'), { exact: true }).fill('Polite formal wording.');
    await campaign.getByLabel(label('Campaign AI behavior', 'Configure explicitly Returning-contact policy'), { exact: true }).check(); await campaign.getByLabel(label('Campaign AI behavior', 'Return to closed conversation with open Lead'), { exact: true }).selectOption('REOPEN_EXISTING'); await campaign.getByLabel(label('Campaign AI behavior', 'Return to closed Lead'), { exact: true }).selectOption('CREATE_NEW');
    await campaign.getByLabel(label('Campaign AI behavior', 'AI behavior edit reason'), { exact: true }).fill('Explicit returning rule <img literal>'); await campaign.getByRole('button', { name: 'Save AI behavior', exact: true }).click(); await expect(campaign).toContainText('Version: 1'); await expect(panel.locator('[data-ai-behavior-effective]')).toContainText('CREATE_NEW');
    await panel.getByLabel('Hypothetical handoff trigger', { exact: true }).selectOption('UNKNOWN_ANSWER'); await panel.getByRole('button', { name: 'Preview AI behavior', exact: true }).click(); const preview = panel.locator('[data-ai-behavior-preview]'); await expect(preview).toContainText('WAITING_FOR_HUMAN'); await expect(preview).toContainText('"notifyManager": true'); await expect(preview).toContainText('"sendAllowed": false'); await expect(preview).toContainText('I am the AI assistant. <img literal>');
    await panel.getByLabel('Hypothetical Lead lifecycle', { exact: true }).selectOption('CLOSED'); await panel.getByRole('button', { name: 'Preview AI behavior', exact: true }).click(); await expect(preview).toContainText('NEW_LEAD_TRUSTED_CONTEXT_REQUIRED');
    await panel.getByLabel('Simulate trusted Campaign reference', { exact: true }).check(); await panel.getByLabel('Simulate trusted required Lead data', { exact: true }).check(); await panel.getByRole('button', { name: 'Preview AI behavior', exact: true }).click(); await expect(preview).toContainText('"action": "CREATE_NEW"'); await expect(preview).toContainText('"mutationsAllowed": false');
    await panel.getByLabel('Hypothetical resolution', { exact: true }).selectOption('AMBIGUOUS'); await panel.getByRole('button', { name: 'Preview AI behavior', exact: true }).click(); await expect(preview).toContainText('RESOLUTION_NOT_UNIQUE');
    await panel.getByLabel('Hypothetical resolution', { exact: true }).selectOption('UNIQUE'); await panel.getByLabel('Hypothetical Lead lifecycle', { exact: true }).selectOption('OPEN'); await panel.getByLabel('Hypothetical controller', { exact: true }).selectOption('HUMAN'); await panel.getByLabel('Hypothetical conversation state', { exact: true }).selectOption('HUMAN_ACTIVE'); await panel.getByRole('button', { name: 'Preview AI behavior', exact: true }).click(); await expect(preview).toContainText('CURRENT_HUMAN_CONTROLLER');
    const saved = await (await page.request.get(root)).json(); expect((await page.request.put(root, { headers: { origin }, data: { version: 0, definition: saved.definition, reason: 'Stale configuration denied' } })).status()).toBe(409);
    const effective = await (await page.request.get('/api/ai/campaigns/' + c.id + '/effective-configuration')).json(); expect(effective.assistantReady).toBe(false); expect(effective.allowedTools).toEqual([]); expect(effective.behavior.sources.disclosure).toBe('BRANCH');
    await campaign.getByLabel(label('Campaign AI behavior', 'Configure explicitly Returning-contact policy'), { exact: true }).uncheck(); await campaign.getByLabel(label('Campaign AI behavior', 'AI behavior edit reason'), { exact: true }).fill('Clear rule retains original history'); await campaign.getByRole('button', { name: 'Save AI behavior', exact: true }).click(); await expect(campaign).toContainText('Version: 2'); await campaign.getByRole('button', { name: 'View past AI behavior 1', exact: true }).click(); await expect(campaign.locator('[data-ai-behavior-version]')).toContainText('CREATE_NEW'); expect(await panel.locator('img').count()).toBe(0);
    await login(agent, 'agent'); expect((await agent.request.get(root)).status()).toBe(403); expect((await agent.request.get(defaults)).status()).toBe(403); expect((await agent.request.post(root + '/preview', { headers: { origin }, data: { branchVersion: effective.behavior.branchVersion, campaignVersion: 2, context: { leadLifecycle: 'OPEN', controllerType: 'AI', conversationState: 'AI_ACTIVE', resolution: 'UNIQUE', explicitCampaignReference: false, requiredLeadData: false, disclosureAlreadySent: false, humanAvailable: false, trigger: 'NONE', misunderstandingCount: 0, qualificationHandoffRequired: false } } })).status()).toBe(403);
    await page.getByRole('combobox', { name: 'Language' }).selectOption('fr'); await expect(panel).toContainText('Politiques de comportement IA'); await page.getByRole('combobox', { name: 'Language' }).selectOption('ar'); await page.setViewportSize({ width: 390, height: 844 }); await campaign.screenshot({ path: '.local/e2e/ai-behavior-campaign-ar.png' }); await branch.screenshot({ path: '.local/e2e/ai-behavior-branch-ar.png' }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true); expect(errors).toEqual([]);
  } finally { await context.close(); await agentContext.close(); }
});
