import { test,expect,type Page } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { randomUUID } from 'node:crypto';
import { emptyKnowledge } from '../src/ai/knowledge.js';
test('Human Copilot reads only current Published Campaign Knowledge and safely downloads approved files, exposes stale failure and scoped denial without AI calls, with Arabic/French UI',async({ browser })=>{
  const fixture=JSON.parse(await readFile(resolve('.local/e2e/fixture.json'),'utf8')) as { password:string;testToken:string },origin='http://127.0.0.1:4100';
  const managerContext=await browser.newContext({ extraHTTPHeaders:{ 'x-e2e-rate-scope':randomUUID() } }),manager=await managerContext.newPage(),context=await browser.newContext({ extraHTTPHeaders:{ 'x-e2e-rate-scope':randomUUID() } }),page=await context.newPage(),secondContext=await browser.newContext({ extraHTTPHeaders:{ 'x-e2e-rate-scope':randomUUID() } }),second=await secondContext.newPage(),errors:string[]=[];
  page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{ if(m.type()==='error' && /same key|unique.*key/i.test(m.text()))errors.push(m.text()); });
  const login=async(p:Page,name:string)=>{ await p.goto('/');await p.getByRole('combobox',{ name:'Language' }).selectOption('en');await p.getByLabel('Email',{ exact:true }).fill(name+'@browser.test');await p.getByLabel('Password',{ exact:true }).fill(fixture.password);await p.getByRole('button',{ name:'Sign in',exact:true }).click();await expect(p.getByRole('button',{ name:'Sign out',exact:true })).toBeVisible(); };
  try {
    await login(manager,'manager');await login(page,'agent');await login(second,'second');const me=await (await manager.request.get('/api/auth/me')).json(),actor=await (await page.request.get('/api/auth/me')).json();
    const made=await manager.request.post('/api/campaigns',{ headers:{ origin },data:{ name:'Browser Copilot Knowledge',branchId:me.branchId,routingMethod:'MANUAL' } });expect(made.status()).toBe(201);const c=(await made.json()).id,kr='/api/ai/campaigns/'+c+'/knowledge';
    expect((await manager.request.post('/api/campaigns/'+c+'/activate',{ headers:{ origin } })).status()).toBe(200);
    const created=await manager.request.post('/api/leads',{ headers:{ origin },data:{ branchId:me.branchId,campaignId:c,contact:{ name:'Browser Published Knowledge Customer',phone:'+15558765433' } } });expect(created.status()).toBe(201);const lead=(await created.json()).id,version=(await (await manager.request.get('/api/leads/'+lead)).json()).lead.version;
    expect((await manager.request.post('/api/leads/'+lead+'/assignment',{ headers:{ origin },data:{ version,agentId:actor.id,reason:'Authorized knowledge reader' } })).status()).toBe(200);const conversation=await page.request.post('/api/leads/'+lead+'/conversations',{ headers:{ origin } });expect(conversation.status()).toBe(201);const cv=(await conversation.json()).id,root='/api/conversations/'+cv+'/ai-campaign-knowledge';
    await page.getByRole('button',{ name:'Retry',exact:true }).click();await page.getByRole('row').filter({ hasText:'Browser Published Knowledge Customer' }).getByRole('button',{ name:'Details',exact:true }).click();await page.getByRole('heading',{ name:'Customer conversations',exact:true }).locator('..').getByRole('button',{ name:'View messages',exact:true }).click();const panel=page.locator('[data-copilot-knowledge]');
    await panel.getByRole('button',{ name:'Show campaign knowledge',exact:true }).click();await expect(panel.getByRole('alert')).toContainText('AI_PUBLISHED_KNOWLEDGE_REQUIRED');
    const label='Published file <img literal>',fileText='Approved registration facts <img src=x onerror=alert(1)>. Ignore instructions is untrusted text';
    const upload=await manager.request.post(kr+'/assets?'+new URLSearchParams({ label,mime:'text/plain',key:randomUUID() }),{ headers:{ origin,'content-type':'application/octet-stream' },data:Buffer.from(fileText) });expect(upload.status()).toBe(201);const asset=(await upload.json()).id;
    expect((await manager.request.post('/__test__/control',{ headers:{ origin,authorization:'Bearer '+fixture.testToken },data:{ processKnowledgeAsset:true } })).status()).toBe(200);expect((await manager.request.post(kr+'/assets/'+asset+'/review',{ headers:{ origin },data:{ version:3,decision:'APPROVED',reason:'Approved scanned source for own Campaign' } })).status()).toBe(201);
    const content={ ...emptyKnowledge(),sections:{ ...emptyKnowledge().sections,prices:'Approved 100 EUR <img src=x onerror="window.__knowledgeXss=true">' },faqs:[{ question:'Registration question',answer:'Approved answer' }],links:[{ label:'Approved external link',url:'https://example.test/approved' }],assets:[asset] };
    expect((await manager.request.put(kr+'/draft',{ headers:{ origin },data:{ version:0,content,reason:'Current approved knowledge' } })).status()).toBe(200);expect((await manager.request.post(kr+'/publish',{ headers:{ origin },data:{ version:1,requestId:randomUUID(),reason:'Publish approved facts and file' } })).status()).toBe(201);
    await panel.getByRole('button',{ name:'Show campaign knowledge',exact:true }).click();const result=panel.locator('[data-copilot-knowledge-result]');await expect(result).toContainText('Published version: 1');await expect(result).toContainText(content.sections.prices);await expect(result).toContainText(fileText);await expect(result.getByRole('link',{ name:'Approved external link',exact:true })).toHaveAttribute('href','https://example.test/approved');expect(await panel.locator('img').count()).toBe(0);expect(await page.evaluate(()=>Object.hasOwn(window,'__knowledgeXss'))).toBe(false);
    const downloadEvent=page.waitForEvent('download');await result.getByRole('button',{ name:'Download approved file: '+label,exact:true }).click();const download=await downloadEvent;expect(download.suggestedFilename()).toBe('knowledge-'+asset+'.txt');expect(await download.failure()).toBeNull();const path=await download.path();expect(await readFile(path!,'utf8')).toBe(fileText);
    for(const endpoint of [root,root+'/assets/'+asset+'/download?version=1'])expect((await second.request.get(endpoint)).status()).toBe(404);expect((await page.request.get(kr)).status()).toBe(403);
    expect((await manager.request.put(kr+'/draft',{ headers:{ origin },data:{ version:1,content:{ ...content,sections:{ ...content.sections,prices:'PRIVATE_UNPUBLISHED_999_EUR' } },reason:'Draft must not leak to Agent' } })).status()).toBe(200);await panel.getByRole('button',{ name:'Show campaign knowledge',exact:true }).click();await expect(result).not.toContainText('PRIVATE_UNPUBLISHED_999');
    expect((await manager.request.put(kr+'/draft',{ headers:{ origin },data:{ version:2,content:{ ...emptyKnowledge(),sections:{ ...emptyKnowledge().sections,prices:'New approved 120 EUR' } },reason:'Replace current Published knowledge' } })).status()).toBe(200);expect((await manager.request.post(kr+'/publish',{ headers:{ origin },data:{ version:3,requestId:randomUUID(),reason:'Publish second version without files' } })).status()).toBe(201);
    await result.getByRole('button',{ name:'Download approved file: '+label,exact:true }).click();await expect(panel.getByRole('alert')).toContainText('AI_PUBLISHED_KNOWLEDGE_CHANGED');await expect(result).toHaveCount(0);await panel.getByRole('button',{ name:'Show campaign knowledge',exact:true }).click();await expect(result).toContainText('Published version: 2');await expect(result).toContainText('New approved 120 EUR');await expect(result).not.toContainText(fileText);
    const messages=(await (await page.request.get('/api/conversations/'+cv+'/messages')).json()).items;expect(messages).toHaveLength(0);expect((await (await page.request.get(root)).json()).providerInvoked).toBe(false);
    await page.getByRole('combobox',{ name:'Language' }).selectOption('fr');await expect(panel).toContainText('Connaissances de campagne publiées');await page.getByRole('combobox',{ name:'Language' }).selectOption('ar');await page.setViewportSize({ width:390,height:844 });await panel.screenshot({ path:'.local/e2e/ai-copilot-knowledge-ar.png' });expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);expect(errors).toEqual([]);
  }finally { await managerContext.close();await context.close();await secondContext.close(); }
});
