import { test,expect,type Page } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { randomUUID } from 'node:crypto';
test('AI Follow-up policy configures current timing, preserves safe scoped history and stops on Human or reply in a write-free Browser preview',async({ browser })=> {
  const fixture=JSON.parse(await readFile(resolve('.local/e2e/fixture.json'),'utf8')) as { password:string };
  const context=await browser.newContext({ extraHTTPHeaders:{ 'x-e2e-rate-scope':randomUUID() } }),agentContext=await browser.newContext({ extraHTTPHeaders:{ 'x-e2e-rate-scope':randomUUID() } }),page=await context.newPage(),agent=await agentContext.newPage(),errors:string[]=[];
  page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{ if(m.type()==='error' && /same key|unique.*key/i.test(m.text()))errors.push(m.text()); });const origin='http://127.0.0.1:4100';
  const login=async(p:Page,name:string)=>{ await p.goto('/');await p.getByRole('combobox',{ name:'Language' }).selectOption('en');await p.getByLabel('Email',{ exact:true }).fill(name+'@browser.test');await p.getByLabel('Password',{ exact:true }).fill(fixture.password);await p.getByRole('button',{ name:'Sign in',exact:true }).click();await expect(p.getByRole('button',{ name:'Sign out',exact:true })).toBeVisible(); };
  try {
    await login(page,'manager');const manager=await (await page.request.get('/api/auth/me')).json();
    const made=await page.request.post('/api/campaigns',{ headers:{ origin },data:{ name:'Browser AI Follow-up Policy',branchId:manager.branchId,routingMethod:'MANUAL' } });expect(made.status()).toBe(201);const c=await made.json(),root='/api/ai/campaigns/'+c.id+'/followup-policy';
    let releaseLoad!:()=>void;const initialLoad=new Promise<void>(resolve=>{ releaseLoad=resolve; });
    await page.route('**'+root,async route=>{ if(route.request().method()==='GET')await initialLoad;await route.continue(); });
    await page.getByRole('button',{ name:'Campaigns',exact:true }).click();await page.getByRole('button',{ name:'Retry',exact:true }).click();await page.getByRole('row').filter({ hasText:'Browser AI Follow-up Policy' }).getByRole('button',{ name:'Details',exact:true }).click();
    const panel=page.locator('[data-campaign-ai-followup]');await expect(panel).toContainText('Version: 0');await expect(panel.getByLabel('Enable AI follow-up policy',{ exact:true })).toBeDisabled();await expect(panel.getByRole('button',{ name:'Save AI follow-up policy',exact:true })).toBeDisabled();releaseLoad();
    await panel.getByLabel('Enable AI follow-up policy',{ exact:true }).check();await panel.getByLabel('Initial AI response delay in seconds',{ exact:true }).fill('5');
    await panel.getByRole('button',{ name:'Add follow-up delay',exact:true }).click();await panel.getByLabel('Follow-up delay in seconds 1',{ exact:true }).fill('10');await panel.getByRole('button',{ name:'Add follow-up delay',exact:true }).click();await panel.getByLabel('Follow-up delay in seconds 2',{ exact:true }).fill('20');
    await panel.getByLabel('Final no-response action',{ exact:true }).selectOption('HANDOFF');await panel.getByLabel('AI follow-up policy reason',{ exact:true }).fill('Current explicit delays <img literal>');await panel.getByRole('button',{ name:'Save AI follow-up policy',exact:true }).click();await expect(panel).toContainText('Version: 1');
    await panel.getByLabel('Simulation anchor time',{ exact:true }).fill('2026-01-01T10:00');await panel.getByRole('button',{ name:'Preview AI follow-up timing',exact:true }).click();const preview=panel.locator('[data-ai-followup-preview]');await expect(preview).toContainText('"decision": "DUE"');await expect(preview).toContainText('"sendAllowed": false');
    await panel.getByLabel('Simulated controller',{ exact:true }).selectOption('HUMAN');await panel.getByRole('button',{ name:'Preview AI follow-up timing',exact:true }).click();await expect(preview).toContainText('AI_CONTROLLER_REQUIRED');
    await panel.getByLabel('Simulated controller',{ exact:true }).selectOption('AI');await panel.getByLabel('Simulate customer reply',{ exact:true }).check();await panel.getByRole('button',{ name:'Preview AI follow-up timing',exact:true }).click();await expect(preview).toContainText('CUSTOMER_REPLIED');
    await panel.getByLabel('Simulate customer reply',{ exact:true }).uncheck();await panel.getByLabel('Simulated sent follow-up count',{ exact:true }).fill('2');await panel.getByRole('button',{ name:'Preview AI follow-up timing',exact:true }).click();await expect(preview).toContainText('"decision": "HANDOFF"');
    const saved=(await (await page.request.get(root)).json()).definition;const effective=await (await page.request.get('/api/ai/campaigns/'+c.id+'/effective-configuration')).json();expect(effective.followup.version).toBe(1);expect(effective.assistantReady).toBe(false);expect(effective.allowedTools).toEqual([]);
    expect((await page.request.put(root,{ headers:{ origin },data:{ version:0,definition:saved,reason:'Stale edit must be rejected' } })).status()).toBe(409);
    await panel.getByLabel('Enable AI follow-up policy',{ exact:true }).uncheck();await panel.getByLabel('AI follow-up policy reason',{ exact:true }).fill('Disable policy preserves timing history');await panel.getByRole('button',{ name:'Save AI follow-up policy',exact:true }).click();await expect(panel).toContainText('Version: 2');
    await panel.getByRole('button',{ name:'View past AI follow-up policy 1',exact:true }).click();await expect(panel.locator('[data-ai-followup-version]')).toContainText('"enabled": true');await expect(panel.locator('[data-ai-followup-version]')).toContainText('20');await expect(panel.locator('img')).toHaveCount(0);
    await login(agent,'agent');expect((await agent.request.get(root)).status()).toBe(403);expect((await agent.request.post(root+'/preview',{ headers:{ origin },data:{ version:2,definition:saved,anchorAt:new Date().toISOString(),attemptsSent:0,hasInboundReply:false,leadLifecycle:'OPEN',controllerType:'AI',conversationState:'AI_ACTIVE' } })).status()).toBe(403);
    await page.getByRole('combobox',{ name:'Language' }).selectOption('fr');await expect(panel).toContainText('Politique de relance IA');await page.getByRole('combobox',{ name:'Language' }).selectOption('ar');await page.setViewportSize({ width:390,height:844 });await panel.screenshot({ path:'.local/e2e/ai-followup-policy-ar.png' });expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);expect(errors).toEqual([]);
  }finally { await context.close();await agentContext.close(); }
});
