import { test,expect,type Page } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { randomUUID } from 'node:crypto';
import { emptyAIOperationalConfig } from '../src/ai/operational-config.js';
import { emptyKnowledge } from '../src/ai/knowledge.js';
test('Campaign AI simulation runs published evidence and unknown handoff through durable provider HTTP, preserves trace/history, blocks stale context and scoped access, with Arabic/French safe UI',async({ browser })=>{
  const fixture=JSON.parse(await readFile(resolve('.local/e2e/fixture.json'),'utf8')) as { password:string;testToken:string };
  const context=await browser.newContext({ extraHTTPHeaders:{ 'x-e2e-rate-scope':randomUUID() } }),agentContext=await browser.newContext({ extraHTTPHeaders:{ 'x-e2e-rate-scope':randomUUID() } }),page=await context.newPage(),agent=await agentContext.newPage(),errors:string[]=[],origin='http://127.0.0.1:4100';
  page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{ if(m.type()==='error' && /same key|unique.*key/i.test(m.text()))errors.push(m.text()); });
  const login=async(p:Page,name:string)=>{ await p.goto('/');await p.getByRole('combobox',{ name:'Language' }).selectOption('en');await p.getByLabel('Email',{ exact:true }).fill(name+'@browser.test');await p.getByLabel('Password',{ exact:true }).fill(fixture.password);await p.getByRole('button',{ name:'Sign in',exact:true }).click();await expect(p.getByRole('button',{ name:'Sign out',exact:true })).toBeVisible(); };
  try {
    await login(page,'manager');const me=await (await page.request.get('/api/auth/me')).json();
    const create=await page.request.post('/api/campaigns',{ headers:{ origin },data:{ name:'Browser AI Simulation',branchId:me.branchId,routingMethod:'MANUAL' } });expect(create.status()).toBe(201);const c=await create.json(),root='/api/ai/campaigns/'+c.id+'/simulations',effective='/api/ai/campaigns/'+c.id+'/effective-configuration';
    const connection=await page.request.post('/api/ai/connections',{ headers:{ origin },data:{ branchId:me.branchId,name:'Browser simulation connection',provider:'OPENAI',credential:'BrowserSyntheticAI_Simulation123',reason:'Dedicated synthetic only' } });expect(connection.status()).toBe(201);const cid=(await connection.json()).id;
    expect((await page.request.post('/api/ai/connections/'+cid+'/test',{ headers:{ origin },data:{ version:1 } })).status()).toBe(200);
    const profile=await page.request.post('/api/ai/profiles',{ headers:{ origin },data:{ connectionId:cid,name:'Browser simulation profile',task:'CONVERSATION',modelId:'Browser-synthetic-model-a',maxOutputTokens:1024,active:true,reason:'Current task model' } });expect(profile.status()).toBe(201);const pid=(await profile.json()).id;
    const config={ ...emptyAIOperationalConfig(),profiles:{ ...emptyAIOperationalConfig().profiles,CONVERSATION:pid },language:{ supported:['en','ar'],preferred:'en',detect:false } };
    expect((await page.request.put('/api/ai/campaigns/'+c.id+'/configuration',{ headers:{ origin },data:{ version:0,definition:config,reason:'Simulation current configuration' } })).status()).toBe(200);
    const publish=async(price:string,version=0)=>{ const kr='/api/ai/campaigns/'+c.id+'/knowledge',content={ ...emptyKnowledge(),sections:{ ...emptyKnowledge().sections,prices:price } };expect((await page.request.put(kr+'/draft',{ headers:{ origin },data:{ version,content,reason:'Approved price' } })).status()).toBe(200);expect((await page.request.post(kr+'/publish',{ headers:{ origin },data:{ version:version+1,requestId:randomUUID(),reason:'Publish tested price' } })).status()).toBe(201); };
    await publish('Approved price 100 EUR <img src=x onerror=alert(1)>');
    let release!:()=>void;const gate=new Promise<void>(r=>release=r);await page.route('**'+effective,async route=>{ if(route.request().method()==='GET')await gate;await route.continue(); });
    await page.getByRole('button',{ name:'Campaigns',exact:true }).click();await page.getByRole('button',{ name:'Retry',exact:true }).click();await page.getByRole('row').filter({ hasText:'Browser AI Simulation' }).getByRole('button',{ name:'Details',exact:true }).click();
    const panel=page.locator('[data-campaign-ai-simulation]');await expect(panel.getByLabel('Sample question',{ exact:true })).toBeDisabled();release();await expect(panel.getByLabel('Sample question',{ exact:true })).toBeEnabled();
    const worker=async()=>{ const r=await page.request.post('/__test__/ai-simulation',{ headers:{ origin,authorization:'Bearer '+fixture.testToken } });expect(r.status()).toBe(200);expect((await r.json()).processed).toBe(true); };
    await panel.getByLabel('Sample question',{ exact:true }).fill('What is the price?');await panel.getByRole('button',{ name:'Run AI simulation',exact:true }).click();const result=panel.locator('[data-ai-simulation-result]');await expect(result).toContainText('Status: QUEUED');await worker();await expect(result).toContainText('Status: COMPLETED');await expect(result).toContainText('Approved price 100 EUR <img src=x onerror=alert(1)>');await expect(result).toContainText('section:prices');await expect(result).toContainText('"sendAllowed": false');expect(await panel.locator('img').count()).toBe(0);
    const first=(await (await page.request.get(root)).json()).items[0];const saved=await (await page.request.get(root+'/'+first.id)).json();expect(saved.knowledge_version).toBe(1);expect(saved.profile.model_id).toBe('Browser-synthetic-model-a');expect(JSON.stringify(saved)).not.toContain('BrowserSyntheticAI_Simulation123');
    await panel.getByLabel('Sample question',{ exact:true }).fill('Unknown registration schedule?');await panel.getByRole('button',{ name:'Run AI simulation',exact:true }).click();await expect(result).toContainText('Status: QUEUED');await worker();await expect(result).toContainText('Recommended Human handoff');await expect(result).toContainText('UNKNOWN_ANSWER');await expect(result).toContainText('requestHumanHandoff');
    await publish('New approved price 120 EUR',1);await panel.getByLabel('Sample question',{ exact:true }).fill('Current price?');await panel.getByRole('button',{ name:'Run AI simulation',exact:true }).click();await expect(panel.getByRole('alert')).toContainText('AI_SIMULATION_CONTEXT_CHANGED');await panel.getByRole('button',{ name:'Reload simulation context',exact:true }).click();await expect(panel.getByLabel('Sample question',{ exact:true })).toBeEnabled();await panel.getByRole('button',{ name:'Run AI simulation',exact:true }).click();await expect(result).toContainText('Status: QUEUED');await worker();await expect(result).toContainText('Published knowledge version: 2');await expect(result).toContainText('New approved price 120 EUR');
    await panel.getByRole('button',{ name:'View simulation '+first.id,exact:true }).click();await expect(result).toContainText('Published knowledge version: 1');await expect(result).toContainText('Approved price 100 EUR');
    await panel.getByLabel('Sample question',{ exact:true }).fill('Provider failure');await panel.getByRole('button',{ name:'Run AI simulation',exact:true }).click();await expect(result).toContainText('Status: QUEUED');await worker();await expect(result).toContainText('Status: FAILED');await expect(result).toContainText('AI_AUTH_FAILED');expect(await panel.innerText()).not.toContain('private synthetic provider failure');
    await login(agent,'agent');expect((await agent.request.get(root)).status()).toBe(403);expect((await agent.request.get(root+'/'+first.id)).status()).toBe(403);expect((await agent.request.post(root,{ headers:{ origin },data:{ requestId:randomUUID(),expectedHash:saved.configuration_hash,question:'Try hidden run' } })).status()).toBe(403);
    expect((await page.request.get(effective)).ok()).toBe(true);expect((await (await page.request.get(effective)).json()).assistantReady).toBe(false);
    await page.getByRole('combobox',{ name:'Language' }).selectOption('fr');await expect(panel).toContainText('Simulation IA de campagne');await page.getByRole('combobox',{ name:'Language' }).selectOption('ar');await page.setViewportSize({ width:390,height:844 });await panel.screenshot({ path:'.local/e2e/ai-simulation-ar.png' });expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);expect(errors).toEqual([]);
  }finally { await context.close();await agentContext.close(); }
});
