import { test, expect, type Page } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { randomUUID } from 'node:crypto';
test('Approved customer AI tools configure isolated inheritance and explicit denial with current CAS, safe Browser history and no activation', async ({ browser }) => {
  const fixture = JSON.parse(await readFile(resolve('.local/e2e/fixture.json'), 'utf8')) as { password: string };
  const context = await browser.newContext({ extraHTTPHeaders: { 'x-e2e-rate-scope': randomUUID() } }), agentContext = await browser.newContext({ extraHTTPHeaders: { 'x-e2e-rate-scope': randomUUID() } }), page = await context.newPage(), agent = await agentContext.newPage(), errors: string[] = [], origin = 'http://127.0.0.1:4100';
  page.on('pageerror', e => errors.push(e.message)); page.on('console', m => { if (m.type() === 'error' && /same key|unique.*key/i.test(m.text())) errors.push(m.text()); });
  const login = async (p: Page, name: string) => { await p.goto('/'); await p.getByRole('combobox', { name: 'Language' }).selectOption('en'); await p.getByLabel('Email', { exact: true }).fill(name + '@browser.test'); await p.getByLabel('Password', { exact: true }).fill(fixture.password); await p.getByRole('button', { name: 'Sign in', exact: true }).click(); await expect(p.getByRole('button', { name: 'Sign out', exact: true })).toBeVisible(); };
  let defaults = '', branchBefore: { definition: { allowedTools: string[] | null } } | null = null, release: () => void = () => {};
  try {
    await login(page, 'manager'); const manager = await (await page.request.get('/api/auth/me')).json(); defaults = '/api/ai/branches/' + manager.branchId + '/tool-defaults'; branchBefore = await (await page.request.get(defaults)).json();
    const created = await page.request.post('/api/campaigns', { headers: { origin }, data: { name: 'Browser Tool Approval Policy', branchId: manager.branchId, routingMethod: 'MANUAL' } }); expect(created.status()).toBe(201); const c = await created.json(), root = '/api/ai/campaigns/' + c.id + '/tool-policy';
    const held = new Promise<void>(r => { release = r; }); await page.route('**' + root, async route => { if (route.request().method() === 'GET') await held; await route.continue(); });
    await page.getByRole('button', { name: 'Campaigns', exact: true }).click(); await page.getByRole('button', { name: 'Retry', exact: true }).click(); await page.getByRole('row').filter({ hasText: 'Browser Tool Approval Policy' }).getByRole('button', { name: 'Details', exact: true }).click();
    const panel = page.locator('[data-campaign-ai-tools]'), branch = panel.locator('[data-ai-tools-scope="BRANCH"]'), campaign = panel.locator('[data-ai-tools-scope="CAMPAIGN"]'), effective = panel.locator('[data-ai-tools-effective]');
    await expect(campaign.getByRole('button', { name: 'Save AI tools', exact: true })).toBeDisabled(); release(); await expect(campaign.getByRole('button', { name: 'Save AI tools', exact: true })).toBeEnabled();
    const label = (scope: 'Branch AI tool defaults' | 'Campaign AI tools', field: string) => scope + ' · ' + field;
    await branch.getByLabel(label('Branch AI tool defaults', 'Tool list source'), { exact: true }).selectOption('EXPLICIT');
    for (const name of ['getCampaignKnowledge','requestHumanHandoff','updateQualificationField']) await branch.getByLabel(label('Branch AI tool defaults', name), { exact: true }).check();
    await branch.getByLabel(label('Branch AI tool defaults', 'Tool approval edit reason'), { exact: true }).fill('Explicit branch approval <img literal>'); await branch.getByRole('button', { name: 'Save AI tools', exact: true }).click(); await expect(effective).toContainText('BRANCH'); await expect(effective).toContainText('updateQualificationField');
    await campaign.getByLabel(label('Campaign AI tools', 'Tool list source'), { exact: true }).selectOption('EXPLICIT'); await campaign.getByLabel(label('Campaign AI tools', 'requestHumanHandoff'), { exact: true }).check();
    await campaign.getByLabel(label('Campaign AI tools', 'Tool approval edit reason'), { exact: true }).fill('Campaign handoff only <img literal>'); await campaign.getByRole('button', { name: 'Save AI tools', exact: true }).click(); await expect(campaign).toContainText('Version: 1'); await expect(effective).toContainText('CAMPAIGN'); await expect(effective).not.toContainText('updateQualificationField');
    const current = await (await page.request.get('/api/ai/campaigns/' + c.id + '/effective-configuration')).json(); expect(current.allowedTools).toEqual(['requestHumanHandoff']); expect(current.assistantReady).toBe(false); expect(current.globalGuardrails.noSecrets).toBe(true);
    expect((await page.request.put(root, { headers: { origin }, data: { version: 1, definition: { allowedTools: false }, reason: 'No implicit type coercion' } })).status()).toBe(400);
    expect((await page.request.put(root, { headers: { origin }, data: { version: 1, definition: { allowedTools: ['confirmPayment'] }, reason: 'No financial authority' } })).status()).toBe(400);
    expect((await page.request.put(root, { headers: { origin }, data: { version: 1, definition: { allowedTools: [] }, reason: 'Current separate administrator revocation' } })).status()).toBe(200);
    await campaign.getByLabel(label('Campaign AI tools', 'Tool approval edit reason'), { exact: true }).fill('Stale UI approval must not restore'); await campaign.getByRole('button', { name: 'Save AI tools', exact: true }).click(); await expect(campaign.getByRole('alert')).toContainText('AI_TOOL_POLICY_VERSION_CONFLICT'); await expect(campaign.locator('[data-ai-tools-version]')).toHaveCount(0); await expect(campaign.getByRole('button', { name: 'Save AI tools', exact: true })).toBeDisabled();
    await campaign.getByRole('button', { name: 'Reload AI tools', exact: true }).click(); await expect(campaign).toContainText('Version: 2'); await expect(effective).toContainText('No approved tools'); await campaign.getByRole('button', { name: 'View past AI tools 1', exact: true }).click(); await expect(campaign.locator('[data-ai-tools-version]')).toContainText('requestHumanHandoff'); await expect(campaign.locator('[data-ai-tools-version]')).toContainText('<img literal>'); expect(await panel.locator('img').count()).toBe(0);
    await page.route('**' + root + '/history', route => route.fulfill({ status: 403, contentType: 'application/json', body: JSON.stringify({ error: 'CURRENT_ACCESS_REVOKED' }) })); await campaign.getByRole('button', { name: 'Reload AI tools', exact: true }).click(); await expect(campaign.getByRole('alert')).toContainText('CURRENT_ACCESS_REVOKED'); await expect(campaign.locator('[data-ai-tools-version]')).toHaveCount(0); await expect(campaign.getByRole('button', { name: 'View past AI tools 1', exact: true })).toHaveCount(0); await page.unroute('**' + root + '/history'); await campaign.getByRole('button', { name: 'Reload AI tools', exact: true }).click();
    await campaign.getByLabel(label('Campaign AI tools', 'Tool list source'), { exact: true }).selectOption('INHERIT'); await campaign.getByLabel(label('Campaign AI tools', 'Tool approval edit reason'), { exact: true }).fill('Restore inherited approval explicitly'); await campaign.getByRole('button', { name: 'Save AI tools', exact: true }).click(); await expect(campaign).toContainText('Version: 3'); await expect(effective).toContainText('BRANCH'); await expect(effective).toContainText('updateQualificationField');
    await login(agent, 'agent'); for (const path of [root, defaults, root + '/history', root + '/versions/1']) expect((await agent.request.get(path)).status()).toBe(403); expect((await agent.request.put(root, { headers: { origin }, data: { version: 3, definition: { allowedTools: [] }, reason: 'Agent cannot reconfigure tools' } })).status()).toBe(403);
    const h = await (await page.request.get(root + '/history?limit=1')).json(); expect(h.items[0].version).toBe(3); expect(h.nextVersion).toBe(3); expect((await (await page.request.get(root + '/history?limit=1&before=3')).json()).items[0].version).toBe(2);
    await page.getByRole('combobox', { name: 'Language' }).selectOption('fr'); await expect(panel).toContainText('Outils IA de conversation approuvés'); await page.getByRole('combobox', { name: 'Language' }).selectOption('ar'); await page.setViewportSize({ width: 390, height: 844 }); await campaign.screenshot({ path: '.local/e2e/ai-tool-policy-ar.png' }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true); expect(errors).toEqual([]);
  } finally {
    release();
    if (defaults && branchBefore) { const response = await page.request.get(defaults); if (response.ok()) { const current = await response.json(); if (JSON.stringify(current.definition) !== JSON.stringify(branchBefore.definition)) expect((await page.request.put(defaults, { headers: { origin }, data: { version: current.version, definition: branchBefore.definition, reason: 'Restore original isolated Browser branch defaults' } })).status()).toBe(200); } }
    await context.close(); await agentContext.close();
  }
});
