import { useEffect,useRef,useState } from 'react';
import { AISharedUse,AIUsableProfiles } from './AISharedUse';
type Api=<T>(path:string,options?:RequestInit)=>Promise<T>;
type Locale='ar'|'en'|'fr';
type Connection={ id:string;name:string;provider:string;branch_id:string|null;version:number;status:string;last_error_code:string|null;capabilities:{ modelCount?:number;catalogVersion?:number;inferenceVerified?:boolean } };
type Profile={ id:string;connection_id:string;name:string;task:string;model_id:string;max_output_tokens:number;active:boolean;version:number;catalog_available:boolean };
type Revision={ version:number;name:string;status:string;reason:string;secret_changed:boolean;created_at:string };
type Probe={ id:string;state:string;connection_version:number;error_code:string|null;created_at:string };
type ProfileHistory={ version:number;created_at:string;snapshot:{ name:string;model_id:string;task:string;active:boolean;reason:string } };
const words={
  title:['إعداد AI','AI setup','Configuration IA'],name:['اسم اتصال AI','AI connection name','Nom de connexion IA'],scope:['نطاق اتصال AI','AI connection scope','Périmètre de connexion IA'],shared:['Organization مشتركة','Organization shared','Organization partagée'],choose:['اختر','Choose','Choisir'],credential:['مفتاح AI API','AI API key','Clé API IA'],reason:['سبب إعداد AI','AI setup reason','Motif de configuration IA'],save:['حفظ اتصال AI','Save AI connection','Enregistrer la connexion IA'],edit:['تعديل اتصال AI','Edit AI connection','Modifier la connexion IA'],test:['اختبار AI authentication وcatalog','Test AI authentication and catalog','Tester authentication IA et catalog'],disable:['تعطيل اتصال AI','Disable AI connection','Désactiver la connexion IA'],reconnect:['إعادة ربط AI','Reconnect AI','Reconnecter IA'],refresh:['تحديث إعداد AI','Refresh AI setup','Actualiser la configuration IA'],history:['تاريخ إعداد AI وفحوصه','AI configuration and test history','Historique de configuration et tests IA'],more:['المزيد','More','Suite'],
  note:['أنشئ credential مخصصة للمؤسسة والمشروع لدى المزود ثم أدخلها هنا. اكتشاف models يثبت authentication/catalog فقط؛ لا يثبت inference أوجاهزية assistant. لا تُرسل بيانات Lead في هذا الاختبار، ولا مفتاح شخصي/Production في الاختبارات المحلية.',
    'Create a dedicated organization/project credential with the provider and enter it here. Model discovery proves authentication/catalog only, not inference or assistant readiness. This test sends no Lead data. Use synthetic keys locally.',
    'Créez une credential dédiée à l’organisation/projet auprès du fournisseur. Découvrir les modèles vérifie seulement authentication/catalog, pas inference ou disponibilité de l’assistant. Aucun Lead envoyé pendant ce test. Utilisez des clés synthétiques localement.'],
  profiles:['AI task profiles','AI task profiles','Profils de tâches IA'],profileName:['اسم AI profile','AI profile name','Nom du profil IA'],task:['مهمة AI profile','AI profile task','Tâche du profil IA'],model:['Model للـAI profile','AI profile model','Modèle du profil IA'],search:['بحث models المتاحة','Search available models','Rechercher les modèles disponibles'],tokens:['حد output tokens','Output token limit','Limite de tokens en sortie'],active:['Profile مفعّلة','Profile enabled','Profil activé'],saveProfile:['حفظ AI profile','Save AI profile','Enregistrer le profil IA'],editProfile:['تعديل AI profile','Edit AI profile','Modifier le profil IA'],profileHistory:['تاريخ AI profile','AI profile history','Historique du profil IA'],cancel:['إلغاء التعديل','Cancel edit','Annuler la modification'],pending:['لم يُتحقق من inference؛ لا AI auto-send بعد','Inference unverified; no AI auto-send yet','Inference non vérifiée ; aucun envoi IA automatique'],
} as const;
export function AISetup({ locale,role,branches,api }:{ locale:Locale;role:'SUPER_ADMIN'|'MANAGER';branches:{ id:string;name:string }[];api:Api }) {
  const index=locale==='ar' ? 0 : locale==='en' ? 1 : 2,t=(key:keyof typeof words)=>words[key][index];
  const [items,setItems]=useState<Connection[]>([]),[cursor,setCursor]=useState<string|null>(null),[profiles,setProfiles]=useState<Profile[]>([]),[profileCursor,setProfileCursor]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [selected,setSelected]=useState<Connection|null>(null),[editing,setEditing]=useState<Connection|null>(null),[name,setName]=useState(''),[scope,setScope]=useState(''),[credential,setCredential]=useState(''),[reason,setReason]=useState('');
  const selectedRef=useRef<string|null>(null);const [revisions,setRevisions]=useState<Revision[]>([]),[probes,setProbes]=useState<Probe[]>([]),[revisionCursor,setRevisionCursor]=useState<string|null>(null),[probeCursor,setProbeCursor]=useState<string|null>(null);
  const [models,setModels]=useState<string[]>([]),[query,setQuery]=useState(''),[modelAfter,setModelAfter]=useState<string|null>(null);
  const [profileEditing,setProfileEditing]=useState<Profile|null>(null),[profileName,setProfileName]=useState(''),[task,setTask]=useState('CONVERSATION'),[model,setModel]=useState(''),[tokens,setTokens]=useState(1024),[active,setActive]=useState(true);
  const [profileHistory,setProfileHistory]=useState<ProfileHistory[]>([]),[historyProfile,setHistoryProfile]=useState<string|null>(null),[historyVersion,setHistoryVersion]=useState<number|null>(null);
  async function load(next:string|null=null) { const p=await api<{ items:Connection[];nextCursor:string|null }>('/api/ai/connections?limit=20'+(next ? '&cursor='+encodeURIComponent(next) : ''));setItems((old)=>next ? [...old,...p.items] : p.items);setCursor(p.nextCursor);setSelected((old)=>p.items.find((c)=>c.id===old?.id) ?? old); }
  async function loadProfiles(next:string|null=null) { const p=await api<{ items:Profile[];nextCursor:string|null }>('/api/ai/profiles?limit=20'+(next ? '&cursor='+encodeURIComponent(next) : ''));setProfiles((old)=>next ? [...old,...p.items] : p.items);setProfileCursor(p.nextCursor); }
  async function modelOptions(c:Connection,q=query,after:string|null=null) { const p=await api<{ items:string[];nextAfter:string|null }>(`/api/ai/connections/${c.id}/models?q=${encodeURIComponent(q)}`+(after ? '&after='+encodeURIComponent(after) : ''));if(selectedRef.current!==c.id)return;setModels((old)=>after ? [...old,...p.items] : p.items);setModelAfter(p.nextAfter); }
  async function detail(c:Connection) { selectedRef.current=c.id;setSelected(c);setProfileEditing(null);setProfileName('');setModel('');setQuery('');setProfileHistory([]);const [h,p]=await Promise.all([api<{ items:Revision[];nextCursor:string|null }>(`/api/ai/connections/${c.id}/history`),api<{ items:Probe[];nextCursor:string|null }>(`/api/ai/connections/${c.id}/probes`)]);if(selectedRef.current!==c.id)return;setRevisions(h.items);setRevisionCursor(h.nextCursor);setProbes(p.items);setProbeCursor(p.nextCursor);await modelOptions(c,''); }
  async function run(fn:()=>Promise<void>) { setBusy(true);setError('');try { await fn(); }catch(e){ setError((e as Error).message); }finally { setBusy(false); } }
  useEffect(()=>{ void run(async()=>{ await Promise.all([load(),loadProfiles()]); }); },[api]);
  async function history(id:string,before:number|null=null) { const p=await api<{ items:ProfileHistory[];nextVersion:number|null }>(`/api/ai/profiles/${id}/history`+(before ? '?before='+before : ''));setHistoryProfile(id);setProfileHistory((old)=>before ? [...old,...p.items] : p.items);setHistoryVersion(p.nextVersion); }
  return <section className="panel ai-setup"><h2>{t('title')}</h2><p>{t('note')}</p><p>Live Verification Pending External Credential/Approval</p>{error && <p role="alert">{error}</p>}
    <form onSubmit={(e)=>{ e.preventDefault();void run(async()=>{ try { await api(editing ? '/api/ai/connections/'+editing.id : '/api/ai/connections',{ method:editing ? 'PUT' : 'POST',body:JSON.stringify(editing ? { name,version:editing.version,reason,...(credential ? { credential } : {}) } : { name,branchId:scope==='SHARED' ? null : scope,provider:'OPENAI',credential,reason }) });setEditing(null);setName('');await load();await loadProfiles(); }finally { setCredential(''); } }); }}>
      <label>{t('name')}<input aria-label={t('name')} required disabled={busy} maxLength={100} value={name} onChange={(e)=>setName(e.target.value)} /></label>
      <label>{t('scope')}<select aria-label={t('scope')} required disabled={busy || !!editing} value={scope} onChange={(e)=>setScope(e.target.value)}><option value="">{t('choose')}</option>{role==='SUPER_ADMIN' && <option value="SHARED">{t('shared')}</option>}{branches.map((b)=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>
      <label>{t('credential')}<input aria-label={t('credential')} type="password" autoComplete="new-password" required={!editing} minLength={16} maxLength={512} disabled={busy} value={credential} onChange={(e)=>setCredential(e.target.value)} /></label>
      <label>{t('reason')}<input aria-label={t('reason')} required minLength={3} maxLength={500} disabled={busy} value={reason} onChange={(e)=>setReason(e.target.value)} /></label><button disabled={busy}>{t('save')}</button>
    </form>{editing && <button disabled={busy} onClick={()=>{ setEditing(null);setName('');setCredential(''); }}>{t('cancel')}</button>}
    <button disabled={busy} onClick={()=>void run(async()=>{ await load();await loadProfiles(); })}>{t('refresh')}</button>
    <ul>{items.map((c)=><li key={c.id} data-ai-connection={c.id}><strong>{c.name} · {c.provider} · {c.status}</strong><p>{branches.find((b)=>b.id===c.branch_id)?.name ?? t('shared')} · {c.capabilities.modelCount ?? 0} models · {c.last_error_code}</p><p>{t('pending')}</p>
      <button disabled={busy || c.status==='DISABLED'} onClick={()=>{ setEditing(c);setName(c.name);setScope(c.branch_id ?? 'SHARED');setCredential('');setReason(''); }}>{t('edit')}</button>
      <button disabled={busy || c.status==='DISABLED'} onClick={()=>void run(async()=>{ await api(`/api/ai/connections/${c.id}/test`,{ method:'POST',body:JSON.stringify({ version:c.version }) });await load();await loadProfiles();await detail(c); })}>{t('test')}</button>
      <button disabled={busy || reason.trim().length<3} onClick={()=>void run(async()=>{ await api(`/api/ai/connections/${c.id}/${c.status==='DISABLED' ? 'reconnect' : 'disable'}`,{ method:'POST',body:JSON.stringify({ version:c.version,reason }) });await load();await loadProfiles();if(selected?.id===c.id){ selectedRef.current=null;setSelected(null); } })}>{t(c.status==='DISABLED' ? 'reconnect' : 'disable')}</button>
      <button disabled={busy} onClick={()=>void run(()=>detail(c))}>{t('history')}</button></li>)}</ul>{cursor && <button disabled={busy} onClick={()=>void run(()=>load(cursor))}>{t('more')}</button>}
    <AIUsableProfiles locale={locale} branches={branches} api={api} />
    {selected && <section data-ai-detail><h3>{selected.name}</h3>{role==='SUPER_ADMIN' && !selected.branch_id && <AISharedUse key={selected.id} locale={locale} connection={selected} branches={branches} api={api} />}<ul>{revisions.map((h)=><li key={h.version}>{h.version} · {h.name} · {h.status} · {h.created_at}<p>{h.reason}</p></li>)}</ul>
      {revisionCursor && <button disabled={busy} onClick={()=>void run(async()=>{ const p=await api<{ items:Revision[];nextCursor:string|null }>(`/api/ai/connections/${selected.id}/history?cursor=${encodeURIComponent(revisionCursor)}`);setRevisions((old)=>[...old,...p.items]);setRevisionCursor(p.nextCursor); })}>{t('more')}</button>}
      <ul>{probes.map((p)=><li key={p.id}>{p.state} · {p.error_code} · {p.created_at}</li>)}</ul>{probeCursor && <button disabled={busy} onClick={()=>void run(async()=>{ const p=await api<{ items:Probe[];nextCursor:string|null }>(`/api/ai/connections/${selected.id}/probes?cursor=${encodeURIComponent(probeCursor)}`);setProbes((old)=>[...old,...p.items]);setProbeCursor(p.nextCursor); })}>{t('more')}</button>}
      <h3>{t('profiles')}</h3><label>{t('search')}<input aria-label={t('search')} maxLength={200} value={query} disabled={busy} onChange={(e)=>setQuery(e.target.value)} /></label><button disabled={busy} onClick={()=>void run(()=>modelOptions(selected))}>{t('search')}</button>
      <form data-ai-profile-form onSubmit={(e)=>{ e.preventDefault();void run(async()=>{ await api('/api/ai/profiles'+(profileEditing ? '/'+profileEditing.id : ''),{ method:profileEditing ? 'PUT' : 'POST',body:JSON.stringify({ connectionId:selected.id,name:profileName,task,modelId:model,maxOutputTokens:tokens,active,reason,...(profileEditing ? { version:profileEditing.version } : {}) }) });setProfileEditing(null);setProfileName('');await loadProfiles(); }); }}>
        <label>{t('profileName')}<input aria-label={t('profileName')} required disabled={busy} maxLength={100} value={profileName} onChange={(e)=>setProfileName(e.target.value)} /></label>
        <label>{t('task')}<select aria-label={t('task')} disabled={busy || !!profileEditing} value={task} onChange={(e)=>setTask(e.target.value)}>{['CONVERSATION','SUMMARIZATION','CLASSIFICATION','ANALYSIS'].map((v)=><option key={v}>{v}</option>)}</select></label>
        <label>{t('model')}<select aria-label={t('model')} required disabled={busy} value={model} onChange={(e)=>setModel(e.target.value)}><option value="">{t('choose')}</option>{model && !models.includes(model) && <option value={model}>{model}</option>}{models.map((m)=><option key={m}>{m}</option>)}</select></label>
        <label>{t('tokens')}<input aria-label={t('tokens')} type="number" min={128} max={16384} required disabled={busy} value={tokens} onChange={(e)=>setTokens(Number(e.target.value))} /></label><label><input type="checkbox" disabled={busy} checked={active} onChange={(e)=>setActive(e.target.checked)} />{t('active')}</label><button disabled={busy || reason.trim().length<3}>{t('saveProfile')}</button>
      </form>{modelAfter && <button disabled={busy} onClick={()=>void run(()=>modelOptions(selected,query,modelAfter))}>{t('more')}</button>}
    </section>}
    <ul>{profiles.map((p)=><li key={p.id} data-ai-profile={p.id}>{p.name} · {p.task} · {p.model_id} · {p.active ? 'ACTIVE' : 'DISABLED'} · catalog: {p.catalog_available ? 'AVAILABLE' : 'UNAVAILABLE'}<p>{t('pending')}</p>
      <button disabled={busy} onClick={()=>void run(async()=>{ const c=items.find((c)=>c.id===p.connection_id);if(!c)throw new Error('Refresh or load the connection page first');await detail(c);setProfileEditing(p);setProfileName(p.name);setTask(p.task);setModel(p.model_id);setTokens(p.max_output_tokens);setActive(p.active);setReason(''); })}>{t('editProfile')}</button>
      <button disabled={busy} onClick={()=>void run(()=>history(p.id))}>{t('profileHistory')}</button></li>)}</ul>{profileCursor && <button disabled={busy} onClick={()=>void run(()=>loadProfiles(profileCursor))}>{t('more')}</button>}
    <ul>{profileHistory.map((h)=><li key={h.version}>{h.version} · {h.snapshot.name} · {h.snapshot.task} · {h.snapshot.model_id} · {h.snapshot.active ? 'ACTIVE' : 'DISABLED'} · {h.created_at}<p>{h.snapshot.reason}</p></li>)}</ul>{historyVersion && historyProfile && <button disabled={busy} onClick={()=>void run(()=>history(historyProfile,historyVersion))}>{t('more')}</button>}
  </section>;
}
