import { useEffect,useState } from 'react';
type Api=<T>(path:string,options?:RequestInit)=>Promise<T>;
type Locale='ar'|'en'|'fr';
const words={ title:['إتاحة اتصال AI المشترك للفروع','Shared AI connection branch use','Usage de connexion IA partagée'],branch:['فرع إتاحة AI','AI use branch','Agence autorisée IA'],active:['الاستخدام المشترك مسموح','Shared use allowed','Usage partagé autorisé'],reason:['سبب إتاحة AI المشتركة','Shared AI use reason','Motif d’autorisation IA'],save:['حفظ إتاحة AI المشتركة','Save shared AI use','Enregistrer autorisation IA'],more:['المزيد من إتاحة AI','More AI grants','Plus d’autorisations'],history:['تاريخ إتاحة AI','AI grant history','Historique des autorisations'],select:['اختر الفرع','Choose branch','Choisir agence'],edit:['تعديل إتاحة AI','Edit AI grant','Modifier autorisation IA'],refresh:['تحديث إتاحة AI','Refresh AI grants','Actualiser autorisations IA'],note:['الإتاحة تسمح باستخدام profiles وmetadata فقط. Manager لا يحصل على credential ولا يغير Connection المشتركة. تعطيل الإتاحة يمنع الاستخدام التالي ويحفظ التاريخ؛ لا يفعّل inference أوAI تلقائيًا.',
  'A grant permits profile use and metadata only. Managers receive no credential or shared connection management rights. Revocation prevents subsequent use and retains history; it does not activate inference or AI.',
  'Autorise uniquement les profils et métadonnées. Le Manager ne reçoit ni credential ni droit de configurer la connexion partagée. La révocation bloque les utilisations suivantes et conserve l’historique ; aucune activation automatique IA.'],usable:['AI profiles المتاحة للفرع','AI profiles usable by branch','Profils IA utilisables par agence'],noProfiles:['لا توجد profiles متاحة لهذا الفرع','No profiles available for this branch','Aucun profil disponible pour cette agence'] } as const;
type Grant={ branch_id:string;branch_name:string;active:boolean;version:number;reason:string };
function translate(locale:Locale) { const index=locale==='ar' ? 0 : locale==='en' ? 1 : 2;return (key:keyof typeof words)=>words[key][index]; }
export function AISharedUse({ locale,connection,branches,api }:{ locale:Locale;connection:{ id:string;version:number };branches:{ id:string;name:string }[];api:Api }) {
  const t=translate(locale),root='/api/ai/connections/'+connection.id+'/branch-use';const [items,setItems]=useState<Grant[]>([]),[after,setAfter]=useState<string|null>(null),[branch,setBranch]=useState(''),[active,setActive]=useState(true),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [history,setHistory]=useState<{ version:number;created_at:string;snapshot:{ branch_id:string;active:boolean;reason:string } }[]>([]),[historyBranch,setHistoryBranch]=useState(''),[before,setBefore]=useState<number|null>(null);
  async function load(next:string|null=null) { const p=await api<{ items:Grant[];nextAfter:string|null }>(root+(next ? '?after='+next : ''));setItems((old)=>next ? [...old,...p.items] : p.items);setAfter(p.nextAfter); }
  async function run(fn:()=>Promise<void>) { setBusy(true);setError('');try { await fn(); }catch(e){ setError((e as Error).message); }finally { setBusy(false); } }
  useEffect(()=>{ void run(()=>load()); },[connection.id,connection.version,api]);
  async function view(id:string,next:number|null=null) { const p=await api<{ items:typeof history;nextVersion:number|null }>(root+'/'+id+'/history'+(next ? '?before='+next : ''));setHistoryBranch(id);setHistory((old)=>next ? [...old,...p.items] : p.items);setBefore(p.nextVersion); }
  return <section data-ai-shared-use><h3>{t('title')}</h3><p>{t('note')}</p>{error && <p role="alert">{error}</p>}
    <form onSubmit={(e)=>{ e.preventDefault();void run(async()=>{ const g=items.find((g)=>g.branch_id===branch);await api(root,{ method:'PUT',body:JSON.stringify({ branchId:branch,active,version:g?.version ?? 0,connectionVersion:connection.version,reason }) });await load();await view(branch); }); }}>
      <label>{t('branch')}<select aria-label={t('branch')} required disabled={busy} value={branch} onChange={(e)=>{ setBranch(e.target.value);setActive(items.find((g)=>g.branch_id===e.target.value)?.active ?? true);setReason(''); }}><option value="">{t('select')}</option>{branches.map((b)=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>
      <label><input type="checkbox" checked={active} disabled={busy} onChange={(e)=>setActive(e.target.checked)} />{t('active')}</label><label>{t('reason')}<input aria-label={t('reason')} required minLength={3} maxLength={500} disabled={busy} value={reason} onChange={(e)=>setReason(e.target.value)} /></label><button disabled={busy}>{t('save')}</button>
    </form><button disabled={busy} onClick={()=>void run(()=>load())}>{t('refresh')}</button>
    <ul>{items.map((g)=><li key={g.branch_id} data-ai-grant={g.branch_id}>{g.branch_name} · {g.active ? 'ACTIVE' : 'REVOKED'} · {g.version}<p>{g.reason}</p><button disabled={busy} onClick={()=>{ setBranch(g.branch_id);setActive(g.active);setReason(''); }}>{t('edit')}</button><button disabled={busy} onClick={()=>void run(()=>view(g.branch_id))}>{t('history')}</button></li>)}</ul>{after && <button disabled={busy} onClick={()=>void run(()=>load(after))}>{t('more')}</button>}
    <ul>{history.map((h)=><li key={h.version}>{h.version} · {h.snapshot.active ? 'ACTIVE' : 'REVOKED'} · {h.created_at}<p>{h.snapshot.reason}</p></li>)}</ul>{before && <button disabled={busy} onClick={()=>void run(()=>view(historyBranch,before))}>{t('more')}</button>}
  </section>;
}
export function AIUsableProfiles({ locale,branches,api }:{ locale:Locale;branches:{ id:string;name:string }[];api:Api }) {
  const t=translate(locale);const [branch,setBranch]=useState(''),[items,setItems]=useState<{ id:string;name:string;task:string;model_id:string;connection_name:string;shared:boolean;catalog_available:boolean }[]>([]),[after,setAfter]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  async function load(next:string|null=null) { if(!branch)return;setBusy(true);setError('');try { const p=await api<{ items:typeof items;nextAfter:string|null }>('/api/ai/usable-profiles?branchId='+branch+(next ? '&after='+next : ''));setItems((old)=>next ? [...old,...p.items] : p.items);setAfter(p.nextAfter); }catch(e){ setError((e as Error).message); }finally { setBusy(false); } }
  useEffect(()=>{ setItems([]);setAfter(null);void load(); },[branch,api]);
  return <section data-ai-usable-profiles><h3>{t('usable')}</h3><label>{t('branch')}<select aria-label={t('branch')} disabled={busy} value={branch} onChange={(e)=>setBranch(e.target.value)}><option value="">{t('select')}</option>{branches.map((b)=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><button disabled={busy || !branch} onClick={()=>void load()}>{t('refresh')}</button>{error && <p role="alert">{error}</p>}
    <ul>{items.map((p)=><li key={p.id} data-ai-usable-profile={p.id}>{p.name} · {p.task} · {p.model_id} · {p.connection_name} · {p.shared ? 'SHARED' : 'BRANCH'} · catalog: {p.catalog_available ? 'AVAILABLE' : 'UNAVAILABLE'}</li>)}</ul>{branch && !items.length && <p>{t('noProfiles')}</p>}{after && <button disabled={busy} onClick={()=>void load(after)}>{t('more')}</button>}
  </section>;
}
