import { useEffect,useRef,useState } from 'react';
type Api=<T>(path:string,options?:RequestInit)=>Promise<T>;
type Locale='ar'|'en'|'fr';
type Item={ id:string;question:string;state:string;knowledge_version:number;created_at:string };
type Detail=Item & { version:number;attempt_count:number;error_code:string|null;context_hash:string;configuration_hash:string;profile:Record<string,unknown>;history:{ version:number;state:string;error_code:string|null }[];
  result:{ decision:string;answer:string;handoffReason:string|null;references:{ id:string;text:string }[];expectedAction:string|null;toolsExecuted:[];sendAllowed:false;mutationsAllowed:false }|null };
const strings={
  en:{ title:'Campaign AI simulation',note:'Test a sample question against published knowledge. This run cannot send a customer message, edit a Lead, or confirm a payment. The displayed answer contains approved evidence only; handoff is a recommendation.',question:'Sample question',run:'Run AI simulation',reload:'Reload simulation context',history:'Simulation history',more:'More simulations',view:'View simulation',status:'Status',knowledge:'Published knowledge version',trace:'Original execution trace',handoff:'Recommended Human handoff',answer:'Approved answer evidence',sources:'Source coverage',failure:'Failure',attempt:'Attempts',empty:'No simulations yet.',pending:'The worker has not completed this run. Status refreshes automatically.',limits:'AI activation has further readiness requirements. A successful simulation does not activate customer AI. Live verification requires dedicated credentials and approval.',retry:'Retry as a new simulation',loading:'Loading current context',readiness:'Simulation requires a current Conversation profile, supported language, and published knowledge.' },
  ar:{ title:'محاكاة AI للحملة',note:'اختبر سؤالًا باستخدام المعرفة المنشورة. التنفيذ لا يرسل رسالة للعميل أو يعدّل Lead أو يؤكد دفعًا. الإجابة تعرض الأدلة المعتمدة فقط؛ التسليم إلى Human توصية.',question:'سؤال للاختبار',run:'تشغيل محاكاة AI',reload:'تحديث سياق المحاكاة',history:'سجل المحاكاة',more:'محاكاة إضافية',view:'عرض المحاكاة',status:'الحالة',knowledge:'نسخة المعرفة المنشورة',trace:'سياق التنفيذ الأصلي',handoff:'توصية التسليم إلى Human',answer:'أدلة الإجابة المعتمدة',sources:'تغطية المصادر',failure:'سبب الفشل',attempt:'المحاولات',empty:'لا توجد محاكاة بعد.',pending:'لم يكتمل التنفيذ. تُحدّث الحالة تلقائيًا.',limits:'تفعيل AI للعملاء يحتاج بقية شروط الجاهزية. نجاح المحاكاة لا يفعّل AI. التحقق Live يحتاج Credentials مخصصة وموافقة.',retry:'إعادة الاختبار كمحاكاة جديدة',loading:'تحميل السياق الحالي',readiness:'المحاكاة تحتاج Conversation profile صالحة ولغة ومعرفة منشورة.' },
  fr:{ title:'Simulation IA de campagne',note:'Testez une question avec les connaissances publiées. Aucun message client, modification de prospect ou confirmation de paiement. La réponse affiche uniquement les preuves approuvées ; le transfert est une recommandation.',question:'Question de test',run:'Lancer la simulation IA',reload:'Actualiser le contexte de simulation',history:'Historique des simulations',more:'Autres simulations',view:'Voir la simulation',status:'État',knowledge:'Version des connaissances publiées',trace:'Contexte original',handoff:'Transfert humain recommandé',answer:'Preuves approuvées de réponse',sources:'Couverture des sources',failure:'Échec',attempt:'Tentatives',empty:'Aucune simulation.',pending:'Le worker poursuit cette simulation. L’état est actualisé automatiquement.',limits:'L’activation IA nécessite les autres conditions. Un test réussi ne l’active pas. La vérification Live exige des secrets dédiés et une approbation.',retry:'Réessayer avec une nouvelle simulation',loading:'Chargement du contexte actuel',readiness:'Profil Conversation valide, langue et connaissances publiées requis.' },
} as const;
export function CampaignAISimulation({ campaignId,locale,api }:{ campaignId:string;locale:Locale;api:Api }) {
  const t=strings[locale],root='/api/ai/campaigns/'+campaignId+'/simulations';
  const [question,setQuestion]=useState(''),[hash,setHash]=useState(''),[available,setAvailable]=useState(false),[items,setItems]=useState<Item[]>([]),[before,setBefore]=useState<string|null>(null),[selected,setSelected]=useState<Detail|null>(null),[busy,setBusy]=useState(true),[ready,setReady]=useState(false),[error,setError]=useState('');
  const epoch=useRef(0),selection=useRef(0),pending=useRef<{ requestId:string;expectedHash:string;question:string }|null>(null);
  async function history(cursor?:string){ const e=epoch.current,r=await api<{ items:Item[];nextBefore:string|null }>(root+(cursor ? '?before='+cursor : ''));if(e!==epoch.current)return;setItems(old=>cursor ? [...old.filter(o=>!r.items.some(n=>n.id===o.id)),...r.items] : r.items);setBefore(r.nextBefore); }
  async function load(){ const e=++epoch.current;selection.current++;setSelected(null);setReady(false);setBusy(true);setError('');try {
    const [context,list]=await Promise.all([api<{ hash:string;knowledge:unknown;effective:{ language:unknown };profiles:{ CONVERSATION:{ available:boolean }|null } }>('/api/ai/campaigns/'+campaignId+'/effective-configuration'),api<{ items:Item[];nextBefore:string|null }>(root)]);
    if(e!==epoch.current)return;setHash(context.hash);setAvailable(Boolean(context.knowledge && context.effective.language && context.profiles.CONVERSATION?.available));setItems(list.items);setBefore(list.nextBefore);setReady(true);
  }catch(f){ if(e===epoch.current)setError((f as Error).message); }finally { if(e===epoch.current)setBusy(false); } }
  useEffect(()=>{ setSelected(null);selection.current++;pending.current=null;void load();return()=>{ epoch.current++;selection.current++; }; },[campaignId,api]);
  async function view(id:string){ const s=++selection.current,e=epoch.current;try { const r=await api<Detail>(root+'/'+id);if(s===selection.current && e===epoch.current){ setSelected(r);setError(''); } }catch(e){ if(s===selection.current)setError((e as Error).message); } }
  const jobId=selected?.id,jobState=selected?.state;
  useEffect(()=>{ if(!jobId || !['QUEUED','RUNNING'].includes(jobState!))return;let stopped=false;const s=selection.current,e=epoch.current;
    const timer=window.setTimeout(()=>{ void api<Detail>(root+'/'+jobId).then(r=>{ if(!stopped && s===selection.current && e===epoch.current){ setSelected(r);void history().catch(()=>{}); } }).catch(f=>{ if(!stopped)setError((f as Error).message); }); },1500);
    return()=>{ stopped=true;window.clearTimeout(timer); }; },[selected,api,campaignId]);
  async function run(){ if(!ready || busy || !available)return;setBusy(true);setError('');const e=epoch.current;
    const payload=pending.current ?? { requestId:crypto.randomUUID(),expectedHash:hash,question:question.trim() };pending.current=payload;
    try { const r=await api<{ id:string }>(root,{ method:'POST',body:JSON.stringify(payload) });if(e!==epoch.current)return;pending.current=null;await view(r.id);await history(); }
    catch(f){ if(e===epoch.current)setError((f as Error).message); }finally { if(e===epoch.current)setBusy(false); }
  }
  return <section className="panel" data-campaign-ai-simulation><h3>{t.title}</h3><p>{t.note}</p><p>{t.limits}</p>{error && <p role="alert">{error}</p>}{!ready && <p role="status">{t.loading}</p>}
    {!available && ready && <p>{t.readiness}</p>}<form onSubmit={e=>{ e.preventDefault();void run(); }}><label>{t.question}<textarea aria-label={t.question} required maxLength={4000} disabled={busy || !ready} value={question} onChange={e=>{ setQuestion(e.target.value);pending.current=null; }} /></label><button disabled={busy || !ready || !available || !question.trim()}>{t.run}</button></form>
    <button disabled={busy} onClick={()=>{ pending.current=null;void load(); }}>{t.reload}</button><h4>{t.history}</h4>{!items.length && <p>{t.empty}</p>}<ul>{items.map(i=><li key={i.id}><p>{i.question}</p><p>{t.status}: {i.state} · {t.knowledge}: {i.knowledge_version}</p><button disabled={busy} onClick={()=>void view(i.id)}>{t.view} {i.id}</button></li>)}</ul>{before && <button disabled={busy} onClick={()=>void history(before).catch(e=>setError((e as Error).message))}>{t.more}</button>}
    {selected && <div data-ai-simulation-result><p>{t.status}: {selected.state} · {t.attempt}: {selected.attempt_count}</p><p>{t.knowledge}: {selected.knowledge_version}</p>{['QUEUED','RUNNING'].includes(selected.state) && <p>{t.pending}</p>}{selected.error_code && <p role="alert">{t.failure}: {selected.error_code}</p>}
      {selected.result && <><h4>{selected.result.decision==='HANDOFF' ? t.handoff : t.answer}</h4>{selected.result.handoffReason && <p>{selected.result.handoffReason} · {selected.result.expectedAction}</p>}<div className="knowledge-content">{selected.result.answer}</div><h4>{t.sources}</h4><ul>{selected.result.references.map(r=><li key={r.id}>{r.id}</li>)}</ul></>}
      <h4>{t.trace}</h4><pre dir="ltr" className="knowledge-content">{JSON.stringify({ configurationHash:selected.configuration_hash,contextHash:selected.context_hash,profile:selected.profile,knowledgeVersion:selected.knowledge_version,history:selected.history,sendAllowed:false,mutationsAllowed:false },null,2)}</pre>
      {['FAILED','BLOCKED','COMPLETED'].includes(selected.state) && <button disabled={busy} onClick={()=>{ pending.current=null;setQuestion(selected.question);void load(); }}>{t.retry}</button>}
    </div>}
  </section>;
}
