import { useEffect,useState } from 'react';
import { FieldInput,type FieldRow } from './LeadFields';
type Api=<T>(path:string,options?:RequestInit)=>Promise<T>;
type Condition={ questionId:string;operator:'ANSWERED'|'EQUALS';value:unknown };
type Definition={ enabled:boolean;questions:{ id:string;prompt:string;fieldId:string|null;required:boolean }[];completion:{ mode:'ALL_REQUIRED'|'CONDITIONS';match:'ALL'|'ANY';conditions:Condition[] };handoff:{ onCompletion:boolean;match:'ALL'|'ANY';conditions:Condition[] } };
const empty=():Definition=>({ enabled:false,questions:[],completion:{ mode:'ALL_REQUIRED',match:'ALL',conditions:[] },handoff:{ onCompletion:false,match:'ALL',conditions:[] } });
const words={ title:['إعداد تأهيل الحملة','Campaign qualification','Qualification de campagne'],note:['المعاينة لا تحفظ Lead أوField ولا تُفعّل AI. معايير الحملة لا تلغي التحويل الإلزامي عند طلب إنسان أوغياب جواب مؤكد.', 'Preview writes no Lead or Field and does not activate AI. Campaign criteria do not override mandatory handoff on a human request or an unknown answer.','L’aperçu ne modifie aucun Lead ou champ et n’active pas l’IA. Les critères ne remplacent pas le transfert obligatoire sur demande humaine ou réponse inconnue.'],
  enabled:['تفعيل تعريف التأهيل','Enable qualification definition','Activer la définition'],prompt:['سؤال التأهيل','Qualification question','Question de qualification'],field:['حقل سؤال التأهيل','Qualification question field','Champ de la question'],unmapped:['سؤال دون حقل','Question without field','Question sans champ'],required:['سؤال مطلوب','Required question','Question obligatoire'],add:['إضافة سؤال تأهيل','Add qualification question','Ajouter une question'],remove:['حذف سؤال تأهيل','Remove qualification question','Retirer la question'],up:['تقديم السؤال','Move question up','Monter la question'],down:['تأخير السؤال','Move question down','Descendre la question'],
  completion:['معيار اكتمال التأهيل','Qualification completion criterion','Critère de complétion'],allRequired:['إجابات جميع الأسئلة المطلوبة','All required questions answered','Toutes les questions obligatoires renseignées'],conditions:['شروط صريحة','Explicit conditions','Conditions explicites'],match:['مطابقة شروط التأهيل','Qualification conditions match','Correspondance des conditions'],all:['كل الشروط','All conditions','Toutes les conditions'],any:['أي شرط','Any condition','Au moins une condition'],handoff:['التحويل للبشري بعد الاكتمال','Handoff on qualification completion','Transfert après complétion'],handoffRules:['شروط تحويل إضافية','Additional handoff conditions','Conditions de transfert supplémentaires'],ruleQuestion:['سؤال الشرط','Condition question','Question de condition'],operator:['عامل الشرط','Condition operator','Opérateur'],answered:['أُجيب السؤال','Question answered','Question renseignée'],equals:['الإجابة تساوي','Answer equals','Réponse égale'],ruleValue:['قيمة الشرط','Condition value','Valeur de condition'],addRule:['إضافة شرط','Add condition','Ajouter condition'],removeRule:['إزالة شرط','Remove condition','Retirer condition'],
  reason:['سبب تعديل التأهيل','Qualification edit reason','Motif de modification'],save:['حفظ تعريف التأهيل','Save qualification definition','Enregistrer la définition'],refresh:['إعادة تحميل التأهيل','Reload qualification','Recharger la qualification'],moreFields:['المزيد من حقول التأهيل','More qualification fields','Plus de champs'],previewAnswer:['إجابة معاينة التأهيل','Qualification preview answer','Réponse d’aperçu'],preview:['معاينة التأهيل','Preview qualification','Aperçu de qualification'],complete:['التأهيل مكتمل','Qualification complete','Qualification complète'],missing:['أسئلة مطلوبة ناقصة','Missing required questions','Questions obligatoires manquantes'],handoffResult:['التحويل للبشري مطلوب','Handoff required','Transfert requis'],yes:['نعم','Yes','Oui'],no:['لا','No','Non'],history:['تاريخ تعريف التأهيل','Qualification definition history','Historique de la définition'],view:['عرض تعريف التأهيل السابق','View past qualification definition','Voir la définition précédente'],more:['المزيد من تاريخ التأهيل','More qualification history','Plus d’historique'] } as const;
export function CampaignQualification({ campaignId,locale,api }:{ campaignId:string;locale:'ar'|'en'|'fr';api:Api }) {
  const t=(key:keyof typeof words)=>words[key][locale==='ar' ? 0 : locale==='en' ? 1 : 2],root='/api/ai/campaigns/'+campaignId+'/qualification';
  const [definition,setDefinition]=useState<Definition>(empty),[version,setVersion]=useState(0),[fields,setFields]=useState<FieldRow[]>([]),[nextField,setNextField]=useState<string|null>(null),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[answers,setAnswers]=useState<Record<string,unknown>>({});
  const [result,setResult]=useState<{ complete:boolean;handoff:boolean;missingQuestionIds:string[] }|null>(null),[history,setHistory]=useState<{ version:number;reason:string;created_at:string }[]>([]),[before,setBefore]=useState<number|null>(null),[viewed,setViewed]=useState<{ version:number;definition:Definition;reason:string }|null>(null);
  async function histories(b:number|null=null) { const p=await api<{ items:typeof history;nextVersion:number|null }>(root+'/history'+(b ? '?before='+b : ''));setHistory((h)=>b ? [...h,...p.items] : p.items);setBefore(p.nextVersion); }
  async function load() { const p=await api<{ version:number;definition:Definition;fields:FieldRow[];nextFieldId:string|null }>(root);setDefinition(p.definition);setVersion(p.version);setFields(p.fields);setNextField(p.nextFieldId);setResult(null);setAnswers({});await histories(); }
  async function run(fn:()=>Promise<void>) { setBusy(true);setError('');try { await fn(); }catch(e){ setError((e as Error).message); }finally { setBusy(false); } }
  useEffect(()=>{ setViewed(null);setReason('');void run(load); },[campaignId,api]);
  const edit=(d:Definition)=>{ setDefinition(d);setResult(null); };
  const valueInput=(questionId:string,value:unknown,change:(v:unknown)=>void,label:string)=> {
    const q=definition.questions.find((q)=>q.id===questionId),field=fields.find((f)=>f.id===q?.fieldId);
    return <label>{label}{field ? <FieldInput field={field} ariaLabel={label} value={value} onChange={(v)=>change(field.field_type==='DATETIME' && typeof v==='string' ? new Date(v).toISOString() : v)} /> : <textarea aria-label={label} maxLength={4000} value={typeof value==='string' ? value : ''} onChange={(e)=>change(e.target.value || null)} />}</label>;
  };
  const rules=(kind:'completion'|'handoff')=> { const config=definition[kind];return <fieldset><legend>{t(kind==='completion' ? 'conditions' : 'handoffRules')}</legend><label>{t('match')}<select value={config.match} onChange={(e)=>edit({ ...definition,[kind]:{ ...config,match:e.target.value as 'ALL'|'ANY' } })}><option value="ALL">{t('all')}</option><option value="ANY">{t('any')}</option></select></label>
    {config.conditions.map((c,i)=><div className="knowledge-entry" key={i}><label>{t('ruleQuestion')} {i+1}<select aria-label={t('ruleQuestion')+' '+kind+' '+(i+1)} value={c.questionId} onChange={(e)=>edit({ ...definition,[kind]:{ ...config,conditions:config.conditions.map((r,j)=>j===i ? { ...r,questionId:e.target.value,value:null } : r) } })}><option value="">—</option>{definition.questions.map((q,j)=><option key={q.id} value={q.id}>{j+1}. {q.prompt}</option>)}</select></label>
      <label>{t('operator')}<select aria-label={t('operator')+' '+kind+' '+(i+1)} value={c.operator} onChange={(e)=>edit({ ...definition,[kind]:{ ...config,conditions:config.conditions.map((r,j)=>j===i ? { ...r,operator:e.target.value as Condition['operator'],value:null } : r) } })}><option value="ANSWERED">{t('answered')}</option><option value="EQUALS">{t('equals')}</option></select></label>
      {c.operator==='EQUALS' && valueInput(c.questionId,c.value,(value)=>edit({ ...definition,[kind]:{ ...config,conditions:config.conditions.map((r,j)=>j===i ? { ...r,value } : r) } }),t('ruleValue')+' '+kind+' '+(i+1))}
      <button type="button" onClick={()=>edit({ ...definition,[kind]:{ ...config,conditions:config.conditions.filter((_,j)=>j!==i) } })}>{t('removeRule')}</button></div>)}<button type="button" disabled={!definition.questions.length || config.conditions.length>=40} onClick={()=>edit({ ...definition,[kind]:{ ...config,conditions:[...config.conditions,{ questionId:definition.questions[0]!.id,operator:'ANSWERED',value:null }] } })}>{t('addRule')}</button></fieldset>;
  };
  return <section className="panel" data-campaign-qualification><h3>{t('title')}</h3><p>{t('note')}</p><p>Version: {version}</p>{error && <p role="alert">{error}</p>}
    <form className="knowledge-form" onSubmit={(e)=>{ e.preventDefault();void run(async()=>{ await api(root,{ method:'PUT',body:JSON.stringify({ version,definition,reason }) });await load(); }); }}><fieldset disabled={busy}>
      <label><input type="checkbox" aria-label={t('enabled')} checked={definition.enabled} onChange={(e)=>edit({ ...definition,enabled:e.target.checked })} />{t('enabled')}</label>
      {definition.questions.map((q,i)=><div className="knowledge-entry" key={q.id} data-qualification-question={q.id}><label>{t('prompt')} {i+1}<input aria-label={t('prompt')+' '+(i+1)} required maxLength={500} value={q.prompt} onChange={(e)=>edit({ ...definition,questions:definition.questions.map((v,j)=>j===i ? { ...v,prompt:e.target.value } : v) })} /></label>
        <label>{t('field')} {i+1}<select aria-label={t('field')+' '+(i+1)} value={q.fieldId ?? ''} onChange={(e)=>{ edit({ ...definition,questions:definition.questions.map((v,j)=>j===i ? { ...v,fieldId:e.target.value || null } : v) });setAnswers((old)=>({ ...old,[q.id]:null })); }}><option value="">{t('unmapped')}</option>{q.fieldId && !fields.some((f)=>f.id===q.fieldId) && <option value={q.fieldId}>{q.fieldId} · UNAVAILABLE</option>}{fields.map((f)=><option key={f.id} value={f.id}>{f.label} · {f.field_type}</option>)}</select></label>
        <label><input type="checkbox" aria-label={t('required')+' '+(i+1)} checked={q.required} onChange={(e)=>edit({ ...definition,questions:definition.questions.map((v,j)=>j===i ? { ...v,required:e.target.checked } : v) })} />{t('required')}</label>
        {(['up','down'] as const).map((dir)=><button key={dir} type="button" disabled={dir==='up' ? i===0 : i===definition.questions.length-1} onClick={()=>{ const questions=[...definition.questions],target=i+(dir==='up' ? -1 : 1);[questions[i],questions[target]]=[questions[target]!,questions[i]!];edit({ ...definition,questions }); }}>{t(dir)}</button>)}
        <button type="button" onClick={()=>edit({ ...definition,questions:definition.questions.filter((_,j)=>j!==i),completion:{ ...definition.completion,conditions:definition.completion.conditions.filter((c)=>c.questionId!==q.id) },handoff:{ ...definition.handoff,conditions:definition.handoff.conditions.filter((c)=>c.questionId!==q.id) } })}>{t('remove')}</button>
      </div>)}<button type="button" disabled={definition.questions.length>=40} onClick={()=>edit({ ...definition,questions:[...definition.questions,{ id:crypto.randomUUID(),prompt:'',fieldId:null,required:true }] })}>{t('add')}</button>
      {nextField && <button type="button" onClick={()=>void run(async()=>{ const p=await api<{ fields:FieldRow[];nextFieldId:string|null }>(root+'?afterFieldId='+nextField);setFields((f)=>[...f,...p.fields.filter((n)=>!f.some((old)=>old.id===n.id))]);setNextField(p.nextFieldId); })}>{t('moreFields')}</button>}
      <label>{t('completion')}<select aria-label={t('completion')} value={definition.completion.mode} onChange={(e)=>edit({ ...definition,completion:{ ...definition.completion,mode:e.target.value as 'ALL_REQUIRED'|'CONDITIONS',match:'ALL',conditions:[] } })}><option value="ALL_REQUIRED">{t('allRequired')}</option><option value="CONDITIONS">{t('conditions')}</option></select></label>{definition.completion.mode==='CONDITIONS' && rules('completion')}
      <label><input type="checkbox" aria-label={t('handoff')} checked={definition.handoff.onCompletion} onChange={(e)=>edit({ ...definition,handoff:{ ...definition.handoff,onCompletion:e.target.checked } })} />{t('handoff')}</label>{rules('handoff')}
      <label>{t('reason')}<input aria-label={t('reason')} required minLength={3} maxLength={500} value={reason} onChange={(e)=>setReason(e.target.value)} /></label><button>{t('save')}</button></fieldset></form>
    <fieldset disabled={busy}><legend>{t('preview')}</legend>{definition.questions.map((q,i)=><div key={q.id}>{valueInput(q.id,answers[q.id],(value)=>{ setAnswers({ ...answers,[q.id]:value });setResult(null); },t('previewAnswer')+' '+(i+1)+' · '+q.prompt)}</div>)}<button disabled={busy} onClick={()=>void run(async()=>setResult(await api(root+'/preview',{ method:'POST',body:JSON.stringify({ version,definition,answers:Object.entries(answers).filter(([id,v])=>definition.questions.some((q)=>q.id===id) && v!==null && v!==undefined && v!=='' && (!Array.isArray(v) || v.length)).map(([questionId,value])=>({ questionId,value })) }) })))}>{t('preview')}</button></fieldset>
    {result && <section data-qualification-preview><p>{t('complete')}: {t(result.complete ? 'yes' : 'no')}</p><p>{t('handoffResult')}: {t(result.handoff ? 'yes' : 'no')}</p><h4>{t('missing')}</h4><ul>{result.missingQuestionIds.map((id)=><li key={id}>{definition.questions.find((q)=>q.id===id)?.prompt}</li>)}</ul></section>}
    <button disabled={busy} onClick={()=>void run(load)}>{t('refresh')}</button><h4>{t('history')}</h4><ul>{history.map((h)=><li key={h.version}>{h.version} · {h.created_at} · {h.reason}<button disabled={busy} onClick={()=>void run(async()=>setViewed(await api(root+'/versions/'+h.version)))}>{t('view')} {h.version}</button></li>)}</ul>{before && <button disabled={busy} onClick={()=>void run(()=>histories(before))}>{t('more')}</button>}
    {viewed && <section data-qualification-version><h4>{t('view')} {viewed.version}</h4><p>{viewed.reason}</p><p>{t('enabled')}: {t(viewed.definition.enabled ? 'yes' : 'no')}</p><ol>{viewed.definition.questions.map((q)=><li key={q.id}>{q.prompt} · {q.required ? t('required') : '—'}</li>)}</ol>
      <p>{t('completion')}: {t(viewed.definition.completion.mode==='ALL_REQUIRED' ? 'allRequired' : 'conditions')}</p><p>{t('handoff')}: {t(viewed.definition.handoff.onCompletion ? 'yes' : 'no')}</p>
      {(['completion','handoff'] as const).map((kind)=><section key={kind}><h5>{t(kind==='completion' ? 'conditions' : 'handoffRules')} · {t(viewed.definition[kind].match==='ALL' ? 'all' : 'any')}</h5><ul>{viewed.definition[kind].conditions.map((c,i)=><li key={i}>{viewed.definition.questions.find((q)=>q.id===c.questionId)?.prompt} · {t(c.operator==='ANSWERED' ? 'answered' : 'equals')}{c.operator==='EQUALS' && ' · '+(typeof c.value==='boolean' ? t(c.value ? 'yes' : 'no') : typeof c.value==='string' || typeof c.value==='number' ? String(c.value) : JSON.stringify(c.value))}</li>)}</ul></section>)}
    </section>}
  </section>;
}
