import { useEffect,useRef,useState } from 'react';
import { CampaignKnowledgeAssets } from './CampaignKnowledgeAssets';
type Api=<T>(path:string,options?:RequestInit)=>Promise<T>;
const sections=['description','product','prices','locations','schedules','availability','requirements','registration','policies'] as const;
type Content={ sections:Record<typeof sections[number],string>;faqs:{ question:string;answer:string }[];allowedClaims:string[];prohibitedClaims:string[];links:{ label:string;url:string }[];assets?:string[] };
type Manifest={ id:string;label:string;mime:string;sha256:string;extractedText:string|null;approvalReason:string };
type Publication={ version:number;draft_version:number;content:Content;reason:string;published_at:string;assets:Manifest[] };
type History={ version:number;draft_version?:number;reason:string;created_at:string };
const empty=():Content=>({ sections:Object.fromEntries(sections.map((k)=>[k,''])) as Content['sections'],faqs:[],allowedClaims:[],prohibitedClaims:[],links:[] });
const words={
  title:['معرفة الحملة','Campaign knowledge','Connaissances de campagne'],note:['Draft لا تُستخدم في إجابات العميل. نشر معرفة معتمدة يحفظ نسخة ثابتة ولا يفعّل AI وحده. الروابط معتمدة كعناوين؛ محتواها الخارجي لا يُقرأ تلقائيًا.',
    'Drafts are excluded from customer answers. Publishing approved knowledge preserves a version and alone does not activate AI. Links are approved references; external contents are not fetched automatically.',
    'Les brouillons sont exclus des réponses clients. La publication approuvée conserve une version et ne suffit pas à activer IA. Les liens sont des références approuvées, sans lecture automatique du contenu externe.'],
  description:['وصف الحملة المعتمد','Knowledge campaign description','Description approuvée'],product:['المنتج والخدمة المعتمدان','Knowledge product and service','Produit et service approuvés'],prices:['الأسعار المعتمدة','Knowledge approved prices','Prix approuvés'],locations:['المواقع المعتمدة','Knowledge approved locations','Lieux approuvés'],schedules:['المواعيد المعتمدة','Knowledge approved schedules','Horaires approuvés'],availability:['قواعد التوفر المعتمدة','Knowledge availability rules','Règles de disponibilité'],requirements:['المتطلبات المعتمدة','Knowledge requirements','Exigences approuvées'],registration:['شروط التسجيل المعتمدة','Knowledge registration conditions','Conditions d’inscription'],policies:['السياسات المعتمدة','Knowledge approved policies','Politiques approuvées'],
  faqs:['FAQs المعتمدة','Approved FAQs','FAQ approuvées'],question:['سؤال Knowledge FAQ','Knowledge FAQ question','Question FAQ'],answer:['جواب Knowledge FAQ','Knowledge FAQ answer','Réponse FAQ'],addFAQ:['إضافة Knowledge FAQ','Add Knowledge FAQ','Ajouter FAQ'],remove:['إزالة العنصر','Remove item','Retirer'],links:['روابط Knowledge المعتمدة','Approved knowledge links','Liens approuvés'],linkLabel:['عنوان رابط Knowledge','Knowledge link label','Libellé du lien'],linkUrl:['URL رابط Knowledge','Knowledge link URL','URL du lien'],addLink:['إضافة رابط Knowledge','Add knowledge link','Ajouter lien'],
  allowed:['Claims المسموحة، واحدة لكل سطر','Allowed claims, one per line','Affirmations autorisées, une par ligne'],prohibited:['Claims الممنوعة، واحدة لكل سطر','Prohibited claims, one per line','Affirmations interdites, une par ligne'],reason:['سبب تعديل أو نشر Knowledge','Knowledge edit or publish reason','Motif de modification ou publication'],save:['حفظ Knowledge Draft','Save knowledge draft','Enregistrer le brouillon'],preview:['معاينة Knowledge Draft','Preview knowledge draft','Aperçu du brouillon'],publish:['نشر Knowledge المعتمدة','Publish approved knowledge','Publier les connaissances approuvées'],refresh:['إعادة تحميل Knowledge','Reload knowledge','Recharger les connaissances'],draft:['نسخة Draft','Draft version','Version du brouillon'],published:['آخر نسخة Published','Current published version','Version publiée actuelle'],none:['لم تُنشر معرفة بعد','No published knowledge yet','Aucune connaissance publiée'],previewTitle:['معاينة فقط، لم تُنشر','Preview only, unpublished','Aperçu uniquement, non publié'],history:['تاريخ Knowledge المنشورة','Published knowledge history','Historique publié'],revisions:['تاريخ Knowledge Draft','Knowledge draft history','Historique des brouillons'],view:['عرض نسخة Knowledge','View knowledge version','Voir la version'],more:['المزيد من التاريخ','More history','Plus d’historique'],unsaved:['احفظ تعديلات Draft قبل النشر','Save draft changes before publishing','Enregistrez les modifications avant publication'],
} as const;
export function CampaignKnowledge({ campaignId,locale,api }:{ campaignId:string;locale:'ar'|'en'|'fr';api:Api }) {
  const index=locale==='ar' ? 0 : locale==='en' ? 1 : 2,t=(key:keyof typeof words)=>words[key][index],root='/api/ai/campaigns/'+campaignId+'/knowledge';
  const [content,setContent]=useState<Content>(empty),[version,setVersion]=useState(0),[published,setPublished]=useState<Publication|null>(null),[saved,setSaved]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [allowed,setAllowed]=useState(''),[prohibited,setProhibited]=useState(''),[preview,setPreview]=useState<Content|null>(null),[previewAssets,setPreviewAssets]=useState<Manifest[]>([]),[viewed,setViewed]=useState<Publication|null>(null);
  const [history,setHistory]=useState<History[]>([]),[historyBefore,setHistoryBefore]=useState<number|null>(null),[revisions,setRevisions]=useState<History[]>([]),[revisionBefore,setRevisionBefore]=useState<number|null>(null);
  const publishRequest=useRef<{ version:number;reason:string;requestId:string }|null>(null);
  const editing=()=>({ ...content,allowedClaims:allowed.split('\n').map((x)=>x.trim()).filter(Boolean),prohibitedClaims:prohibited.split('\n').map((x)=>x.trim()).filter(Boolean) });
  const dirty=JSON.stringify(editing())!==saved;
  async function histories(kind:'history'|'revisions',before:number|null=null) { const p=await api<{ items:History[];nextVersion:number|null }>(root+'/'+kind+(before ? '?before='+before : ''));if(kind==='history'){ setHistory((old)=>before ? [...old,...p.items] : p.items);setHistoryBefore(p.nextVersion); }else { setRevisions((old)=>before ? [...old,...p.items] : p.items);setRevisionBefore(p.nextVersion); } }
  async function load() { const p=await api<{ draft:{ version:number;content:Content };published:Publication|null }>(root);setContent(p.draft.content);setVersion(p.draft.version);setSaved(JSON.stringify(p.draft.content));setAllowed(p.draft.content.allowedClaims.join('\n'));setProhibited(p.draft.content.prohibitedClaims.join('\n'));setPublished(p.published);setPreview(null);await Promise.all([histories('history'),histories('revisions')]); }
  async function run(fn:()=>Promise<void>) { setBusy(true);setError('');try { await fn(); }catch(e){ setError((e as Error).message); }finally { setBusy(false); } }
  useEffect(()=>{ void run(load); },[campaignId,api]);
  function render(c:Content,assets:Manifest[]=[]) { return <div className="knowledge-content">{assets.map((a)=><section key={a.id} data-knowledge-manifest={a.id}><h4>{a.label}</h4><p>{a.mime} · SHA256 {a.sha256}</p>{a.extractedText && <p>{a.extractedText}</p>}<p>{a.approvalReason}</p><a href={root+'/assets/'+a.id+'/download'} download>{a.label}</a></section>)}{sections.filter((k)=>c.sections[k]).map((k)=><section key={k}><h4>{t(k)}</h4><p>{c.sections[k]}</p></section>)}{c.faqs.length>0 && <section><h4>{t('faqs')}</h4>{c.faqs.map((f,i)=><div key={i}><strong>{f.question}</strong><p>{f.answer}</p></div>)}</section>}
    {c.allowedClaims.length>0 && <section><h4>{t('allowed')}</h4><ul>{c.allowedClaims.map((s,i)=><li key={i}>{s}</li>)}</ul></section>}{c.prohibitedClaims.length>0 && <section><h4>{t('prohibited')}</h4><ul>{c.prohibitedClaims.map((s,i)=><li key={i}>{s}</li>)}</ul></section>}
    {c.links.length>0 && <section><h4>{t('links')}</h4><ul>{c.links.map((l,i)=><li key={i}><a href={l.url} target="_blank" rel="noopener noreferrer">{l.label}</a></li>)}</ul></section>}</div>; }
  return <section className="panel" data-campaign-knowledge><h3>{t('title')}</h3><p>{t('note')}</p><p>{t('draft')}: <strong>{version}</strong> · {t('published')}: <strong>{published?.version ?? '—'}</strong></p>{error && <p role="alert">{error}</p>}
    <form className="knowledge-form" onSubmit={(e)=>{ e.preventDefault();void run(async()=>{ await api(root+'/draft',{ method:'PUT',body:JSON.stringify({ version,content:editing(),reason }) });await load();publishRequest.current=null; }); }}>
      {sections.map((k)=><label key={k}>{t(k)}<textarea aria-label={t(k)} value={content.sections[k]} maxLength={8000} disabled={busy} onChange={(e)=>{ setContent({ ...content,sections:{ ...content.sections,[k]:e.target.value } });setPreview(null); }} /></label>)}
      <fieldset><legend>{t('faqs')}</legend>{content.faqs.map((f,i)=><div key={i} className="knowledge-entry"><label>{t('question')} {i+1}<input aria-label={t('question')+' '+(i+1)} required maxLength={500} disabled={busy} value={f.question} onChange={(e)=>setContent({ ...content,faqs:content.faqs.map((x,j)=>j===i ? { ...x,question:e.target.value } : x) })} /></label>
        <label>{t('answer')} {i+1}<textarea aria-label={t('answer')+' '+(i+1)} required maxLength={4000} disabled={busy} value={f.answer} onChange={(e)=>setContent({ ...content,faqs:content.faqs.map((x,j)=>j===i ? { ...x,answer:e.target.value } : x) })} /></label><button type="button" disabled={busy} onClick={()=>setContent({ ...content,faqs:content.faqs.filter((_,j)=>j!==i) })}>{t('remove')}</button></div>)}<button type="button" disabled={busy || content.faqs.length>=40} onClick={()=>setContent({ ...content,faqs:[...content.faqs,{ question:'',answer:'' }] })}>{t('addFAQ')}</button></fieldset>
      <label>{t('allowed')}<textarea aria-label={t('allowed')} disabled={busy} maxLength={40079} value={allowed} onChange={(e)=>setAllowed(e.target.value)} /></label><label>{t('prohibited')}<textarea aria-label={t('prohibited')} disabled={busy} maxLength={40079} value={prohibited} onChange={(e)=>setProhibited(e.target.value)} /></label>
      <fieldset><legend>{t('links')}</legend>{content.links.map((l,i)=><div key={i} className="knowledge-entry"><label>{t('linkLabel')} {i+1}<input aria-label={t('linkLabel')+' '+(i+1)} required maxLength={200} disabled={busy} value={l.label} onChange={(e)=>setContent({ ...content,links:content.links.map((x,j)=>j===i ? { ...x,label:e.target.value } : x) })} /></label>
        <label>{t('linkUrl')} {i+1}<input aria-label={t('linkUrl')+' '+(i+1)} type="url" required maxLength={2048} disabled={busy} value={l.url} onChange={(e)=>setContent({ ...content,links:content.links.map((x,j)=>j===i ? { ...x,url:e.target.value } : x) })} /></label><button type="button" disabled={busy} onClick={()=>setContent({ ...content,links:content.links.filter((_,j)=>j!==i) })}>{t('remove')}</button></div>)}<button type="button" disabled={busy || content.links.length>=30} onClick={()=>setContent({ ...content,links:[...content.links,{ label:'',url:'' }] })}>{t('addLink')}</button></fieldset>
      <CampaignKnowledgeAssets campaignId={campaignId} locale={locale} api={api} selected={content.assets ?? []} disabled={busy} onChange={(assets)=>{ setContent({ ...content,assets });setPreview(null); }} />
      <label>{t('reason')}<input aria-label={t('reason')} required minLength={3} maxLength={500} disabled={busy} value={reason} onChange={(e)=>setReason(e.target.value)} /></label><button disabled={busy}>{t('save')}</button>
    </form><div className="actions"><button disabled={busy} onClick={()=>void run(async()=>{ const p=await api<{ content:Content;assets:Manifest[] }>(root+'/preview',{ method:'POST',body:JSON.stringify({ version,content:editing() }) });setPreview(p.content);setPreviewAssets(p.assets); })}>{t('preview')}</button>
      <button disabled={busy || version===0 || dirty || reason.trim().length<3 || published?.draft_version===version} onClick={()=>void run(async()=>{ if(!publishRequest.current || publishRequest.current.version!==version || publishRequest.current.reason!==reason)publishRequest.current={ version,reason,requestId:crypto.randomUUID() };await api(root+'/publish',{ method:'POST',body:JSON.stringify(publishRequest.current) });await load(); })}>{t('publish')}</button>
      <button disabled={busy} onClick={()=>void run(load)}>{t('refresh')}</button></div>{dirty && <p>{t('unsaved')}</p>}
    {preview && <section data-knowledge-preview><h4>{t('previewTitle')}</h4>{render(preview,previewAssets)}</section>}
    <section data-knowledge-published><h4>{t('published')} {published?.version}</h4>{published ? <>{render(published.content,published.assets)}<p>{published.published_at} · {published.reason}</p></> : <p>{t('none')}</p>}</section>
    <h4>{t('history')}</h4><ul>{history.map((h)=><li key={h.version}>{h.version} · Draft {h.draft_version} · {h.created_at}<p>{h.reason}</p><button disabled={busy} onClick={()=>void run(async()=>setViewed(await api<Publication>(root+'/versions/'+h.version)))}>{t('view')} {h.version}</button></li>)}</ul>{historyBefore && <button disabled={busy} onClick={()=>void run(()=>histories('history',historyBefore))}>{t('more')}</button>}
    {viewed && <section data-knowledge-version><h4>{t('view')} {viewed.version}</h4>{render(viewed.content,viewed.assets)}<p>{viewed.reason}</p></section>}
    <h4>{t('revisions')}</h4><ul>{revisions.map((h)=><li key={h.version}>{h.version} · {h.created_at}<p>{h.reason}</p></li>)}</ul>{revisionBefore && <button disabled={busy} onClick={()=>void run(()=>histories('revisions',revisionBefore))}>{t('more')}</button>}
  </section>;
}
