import { useEffect, useRef, useState } from 'react';
type Api = <T>(path: string, options?: RequestInit) => Promise<T>;
type Locale = 'ar' | 'en' | 'fr';
type Policy = { formality: string | null; disclosure: { mode: 'FIRST_AI_MESSAGE' | 'EVERY_AI_MESSAGE'; text: string } | null;
  handoff: { initialContactWithoutAgent: boolean; transitionMessage: string | null; misunderstandingLimit: number | null } | null;
  returningContact: { closedConversation: 'REVIEW' | 'REOPEN_EXISTING'; closedLead: 'REVIEW' | 'REOPEN_EXISTING' | 'CREATE_NEW' } | null };
const empty = (): Policy => ({ formality: null, disclosure: null, handoff: null, returningContact: null });
const words = {
  title: ['سياسات سلوك AI', 'AI behavior policies', 'Politiques de comportement IA'], branch: ['سلوك AI الافتراضي للفرع', 'Branch AI behavior defaults', 'Comportement IA par défaut de l’agence'], campaign: ['سلوك AI للحملة', 'Campaign AI behavior', 'Comportement IA de campagne'],
  note: ['الإعداد والمعاينة لا يفعلان AI ولا يغيران Lead أو محادثة ولا يرسلان رسالة. null تعني وراثة الفرع؛ سياسة العميل العائد خاصة بالحملة. النبرة وإرشادات العلامة تستخدم إعداد AI الحالي. تتطلب الإفصاحات مراجعة السياسة القانونية والتشغيلية المعتمدة.', 'Configuration and preview do not activate AI, change a Lead or conversation, or send a message. Unset values inherit the Branch; returning-contact rules belong to the Campaign. Tone and brand guidance use existing AI settings. Review disclosure against approved legal and operational policy.', 'Configurer et prévisualiser n’active pas l’IA, ne modifie aucun Lead ni conversation et n’envoie aucun message. Les valeurs non définies héritent de l’agence ; les règles de retour appartiennent à la campagne. Le ton utilise les paramètres IA existants. Validez la divulgation selon la politique légale et opérationnelle.'],
  explicit: ['إعداد صريح', 'Configure explicitly', 'Configurer explicitement'], formality: ['درجة الرسمية وإرشاداتها', 'Formality guidance', 'Consignes de formalité'], disclosure: ['تعريف هوية AI', 'AI identity disclosure', 'Divulgation de l’identité IA'], mode: ['متى يظهر التعريف', 'Disclosure placement', 'Quand afficher la divulgation'], first: ['أول رسالة AI', 'First AI message', 'Premier message IA'], every: ['كل رسالة AI', 'Every AI message', 'Chaque message IA'], text: ['نص التعريف المعتمد', 'Approved disclosure text', 'Texte de divulgation approuvé'],
  handoff: ['سياسة التحويل البشري', 'Human handoff policy', 'Politique de transfert humain'], initial: ['السماح بتواصل AI أولي دون Agent مع انتظار الموظف وتنبيه Manager', 'Allow initial AI contact without Agent with Human waiting and Manager attention', 'Autoriser un premier contact IA sans Agent avec attente humaine et alerte Manager'], transition: ['رسالة انتقال معتمدة (اختيارية)', 'Approved transition message (optional)', 'Message de transition approuvé (facultatif)'], limit: ['عدد سوء الفهم قبل التحويل (اختياري)', 'Misunderstanding count before handoff (optional)', 'Nombre de malentendus avant transfert (facultatif)'],
  returning: ['سياسة Contact العائدة', 'Returning-contact policy', 'Politique de retour du Contact'], closedConversation: ['عودة إلى Conversation مغلقة وLead مفتوحة', 'Return to closed conversation with open Lead', 'Retour à une conversation fermée avec Lead ouvert'], closedLead: ['عودة إلى Lead مغلقة', 'Return to closed Lead', 'Retour à un Lead fermé'], review: ['المراجعة / Needs Attention', 'Review / Needs Attention', 'Revue / Needs Attention'], reopen: ['إعادة فتح السجل الحالي وفق القواعد', 'Reopen existing record through rules', 'Rouvrir le dossier existant selon les règles'], create: ['Lead جديدة وفق قاعدة صريحة وسياق موثوق', 'New Lead with explicit rule and trusted context', 'Nouveau Lead avec règle explicite et contexte fiable'],
  guard: ['الغموض وLead المؤرشفة يذهبان للمراجعة. إنشاء Lead جديدة يتطلب مطابقة وحيدة ومرجع Campaign صريحًا وبيانات الحقول المطلوبة الموثوقة. Human takeover وhandoff لا يعيدان AI تلقائيًا؛ لا إسناد عشوائي عند غياب موظف. نقص جواب مؤكد وطلب موظف والشكاوى والحالات الحساسة تفرض التحويل.', 'Ambiguous or archived Leads require review. A new Lead requires unique resolution, an explicit Campaign reference and trusted required-field data. Human takeover and handoff never restart AI automatically; no random assignment without an eligible Human. Unknown answers, Human requests, complaints and sensitive cases require handoff.', 'Les Leads ambigus ou archivés exigent une revue. Un nouveau Lead exige une résolution unique, une référence explicite à la campagne et les données requises fiables. La reprise humaine et le transfert ne réactivent jamais l’IA ; aucune attribution aléatoire. Les réponses inconnues, demandes humaines, plaintes et cas sensibles exigent un transfert.'],
  reason: ['سبب تعديل سلوك AI', 'AI behavior edit reason', 'Motif de modification du comportement IA'], save: ['حفظ سلوك AI', 'Save AI behavior', 'Enregistrer le comportement IA'], reload: ['إعادة تحميل سلوك AI', 'Reload AI behavior', 'Recharger le comportement IA'], version: ['النسخة', 'Version', 'Version'], past: ['عرض سلوك AI السابق', 'View past AI behavior', 'Voir comportement IA précédent'], more: ['المزيد من تاريخ السلوك', 'More AI behavior history', 'Plus d’historique IA'],
  effective: ['السلوك الفعلي ومصدره', 'Effective behavior and source', 'Comportement effectif et source'], refresh: ['تحديث السلوك الفعلي', 'Refresh effective behavior', 'Actualiser le comportement effectif'], simulation: ['معاينة افتراضية للسياسة المحفوظة', 'Hypothetical saved-policy preview', 'Aperçu hypothétique de la politique enregistrée'], preview: ['معاينة سلوك AI', 'Preview AI behavior', 'Prévisualiser le comportement IA'],
  lifecycle: ['حالة Lead المفترضة', 'Hypothetical Lead lifecycle', 'Cycle hypothétique du Lead'], controller: ['التحكم المفترض', 'Hypothetical controller', 'Contrôle hypothétique'], state: ['حالة Conversation المفترضة', 'Hypothetical conversation state', 'État hypothétique de conversation'], resolution: ['نتيجة المطابقة المفترضة', 'Hypothetical resolution', 'Résolution hypothétique'], reference: ['محاكاة مرجع Campaign موثوق', 'Simulate trusted Campaign reference', 'Simuler référence de campagne fiable'], required: ['محاكاة بيانات Lead المطلوبة الموثوقة', 'Simulate trusted required Lead data', 'Simuler données Lead requises fiables'], disclosed: ['محاكاة تعريف AI سبق إرساله', 'Simulate disclosure already sent', 'Simuler divulgation déjà envoyée'], human: ['محاكاة توفر موظف مؤهل', 'Simulate eligible Human available', 'Simuler disponibilité humaine admissible'], trigger: ['سبب تحويل مفترض', 'Hypothetical handoff trigger', 'Motif hypothétique de transfert'], count: ['عدد سوء الفهم المفترض', 'Hypothetical misunderstanding count', 'Nombre hypothétique de malentendus'], qualified: ['محاكاة تحقق معيار Qualification للتحويل', 'Simulate Qualification handoff criteria met', 'Simuler critères de transfert Qualification remplis'],
} as const;
const translate = (locale: Locale) => (key: keyof typeof words) => words[key][locale === 'ar' ? 0 : locale === 'en' ? 1 : 2];
function Editor({ scope, id, locale, api, onChanged }: { scope: 'BRANCH' | 'CAMPAIGN'; id: string; locale: Locale; api: Api; onChanged: () => Promise<void> }) {
  const t = translate(locale), prefix = t(scope === 'BRANCH' ? 'branch' : 'campaign'), root = scope === 'BRANCH' ? '/api/ai/branches/' + id + '/behavior-defaults' : '/api/ai/campaigns/' + id + '/behavior-policy';
  const [policy, setPolicy] = useState<Policy>(empty), [version, setVersion] = useState(0), [reason, setReason] = useState(''), [busy, setBusy] = useState(true), [ready, setReady] = useState(false), [error, setError] = useState('');
  const [history, setHistory] = useState<{ items: { version: number; reason: string; created_at: string }[]; nextVersion: number | null }>({ items: [], nextVersion: null }), [past, setPast] = useState<{ version: number; definition: Policy } | null>(null);
  const loadSequence = useRef(0), label = (key: keyof typeof words) => prefix + ' · ' + t(key);
  async function load() { const n = ++loadSequence.current, [p, h] = await Promise.all([api<{ version: number; definition: Policy }>(root), api<typeof history>(root + '/history')]); if (n !== loadSequence.current) return; setPolicy(p.definition); setVersion(p.version); setHistory(h); setPast(null); setReady(true); }
  async function run(work: () => Promise<void>) { setBusy(true); setError(''); try { await work(); } catch (e) { setError(String(e)); } finally { setBusy(false); } }
  useEffect(() => { let active = true; setReady(false); setBusy(true); void load().catch(e => { if (active) setError(String(e)); }).finally(() => { if (active) setBusy(false); }); return () => { active = false; ++loadSequence.current; }; }, [root]);
  const returningOptions = (withCreate: boolean) => <><option value="REVIEW">{t('review')}</option><option value="REOPEN_EXISTING">{t('reopen')}</option>{withCreate && <option value="CREATE_NEW">{t('create')}</option>}</>;
  return <section data-ai-behavior-scope={scope}><h4>{prefix}</h4><small>{t('version')}: {version}</small>{error && <p role="alert" className="error">{error}</p>}
    <form onSubmit={e => { e.preventDefault(); void run(async () => { await api(root, { method: 'PUT', body: JSON.stringify({ version, definition: policy, reason }) }); await load(); setReason(''); await onChanged(); }); }}>
      <fieldset className="knowledge-form" disabled={busy || !ready}>
        <label className="check-row"><input aria-label={label('explicit') + ' ' + t('formality')} type="checkbox" checked={policy.formality !== null} onChange={e => setPolicy({ ...policy, formality: e.target.checked ? '' : null })} />{t('explicit')} · {t('formality')}</label>
        {policy.formality !== null && <label>{t('formality')}<textarea aria-label={label('formality')} maxLength={1000} value={policy.formality} onChange={e => setPolicy({ ...policy, formality: e.target.value })} /></label>}
        <label className="check-row"><input aria-label={label('explicit') + ' ' + t('disclosure')} type="checkbox" checked={policy.disclosure !== null} onChange={e => setPolicy({ ...policy, disclosure: e.target.checked ? { mode: 'FIRST_AI_MESSAGE', text: '' } : null })} />{t('explicit')} · {t('disclosure')}</label>
        {policy.disclosure && <><label>{t('mode')}<select aria-label={label('mode')} value={policy.disclosure.mode} onChange={e => setPolicy({ ...policy, disclosure: { ...policy.disclosure!, mode: e.target.value as 'FIRST_AI_MESSAGE' | 'EVERY_AI_MESSAGE' } })}><option value="FIRST_AI_MESSAGE">{t('first')}</option><option value="EVERY_AI_MESSAGE">{t('every')}</option></select></label><label>{t('text')}<textarea aria-label={label('text')} required minLength={3} maxLength={2000} value={policy.disclosure.text} onChange={e => setPolicy({ ...policy, disclosure: { ...policy.disclosure!, text: e.target.value } })} /></label></>}
        <label className="check-row"><input aria-label={label('explicit') + ' ' + t('handoff')} type="checkbox" checked={policy.handoff !== null} onChange={e => setPolicy({ ...policy, handoff: e.target.checked ? { initialContactWithoutAgent: false, transitionMessage: null, misunderstandingLimit: null } : null })} />{t('explicit')} · {t('handoff')}</label>
        {policy.handoff && <><label className="check-row"><input aria-label={label('initial')} type="checkbox" checked={policy.handoff.initialContactWithoutAgent} onChange={e => setPolicy({ ...policy, handoff: { ...policy.handoff!, initialContactWithoutAgent: e.target.checked } })} />{t('initial')}</label>
          <label>{t('transition')}<textarea aria-label={label('transition')} maxLength={2000} value={policy.handoff.transitionMessage ?? ''} onChange={e => setPolicy({ ...policy, handoff: { ...policy.handoff!, transitionMessage: e.target.value || null } })} /></label>
          <label>{t('limit')}<input aria-label={label('limit')} type="number" min={1} max={2147483647} step={1} value={policy.handoff.misunderstandingLimit ?? ''} onChange={e => setPolicy({ ...policy, handoff: { ...policy.handoff!, misunderstandingLimit: e.target.value ? Number(e.target.value) : null } })} /></label></>}
        {scope === 'CAMPAIGN' && <><label className="check-row"><input aria-label={label('explicit') + ' ' + t('returning')} type="checkbox" checked={policy.returningContact !== null} onChange={e => setPolicy({ ...policy, returningContact: e.target.checked ? { closedConversation: 'REVIEW', closedLead: 'REVIEW' } : null })} />{t('explicit')} · {t('returning')}</label>
          {policy.returningContact && <><label>{t('closedConversation')}<select aria-label={label('closedConversation')} value={policy.returningContact.closedConversation} onChange={e => setPolicy({ ...policy, returningContact: { ...policy.returningContact!, closedConversation: e.target.value as 'REVIEW' | 'REOPEN_EXISTING' } })}>{returningOptions(false)}</select></label><label>{t('closedLead')}<select aria-label={label('closedLead')} value={policy.returningContact.closedLead} onChange={e => setPolicy({ ...policy, returningContact: { ...policy.returningContact!, closedLead: e.target.value as 'REVIEW' | 'REOPEN_EXISTING' | 'CREATE_NEW' } })}>{returningOptions(true)}</select></label></>}
        </>}
        <label>{t('reason')}<input aria-label={label('reason')} required minLength={3} maxLength={500} value={reason} onChange={e => setReason(e.target.value)} /></label><button>{t('save')}</button>
      </fieldset>
    </form><button disabled={busy} onClick={() => void run(async () => { await load(); await onChanged(); })}>{t('reload')}</button>
    <ul className="timeline">{history.items.map(h => <li key={h.version}><span>{h.reason}<button className="link" disabled={busy} onClick={() => void run(async () => { setPast(await api(root + '/versions/' + h.version)); })}>{t('past')} {h.version}</button></span><time dir="auto">{new Date(h.created_at).toLocaleString(locale)}</time></li>)}</ul>
    {history.nextVersion && <button disabled={busy} onClick={() => void run(async () => { const more = await api<typeof history>(root + '/history?before=' + history.nextVersion); setHistory(h => ({ items: [...h.items, ...more.items], nextVersion: more.nextVersion })); })}>{t('more')}</button>}
    {past && <pre className="knowledge-content" data-ai-behavior-version>{JSON.stringify(past, null, 2)}</pre>}
  </section>;
}
const initialContext = () => ({ leadLifecycle: 'OPEN', controllerType: 'AI', conversationState: 'AI_ACTIVE', resolution: 'UNIQUE', explicitCampaignReference: false, requiredLeadData: false, disclosureAlreadySent: false, humanAvailable: false, trigger: 'NONE', misunderstandingCount: 0, qualificationHandoffRequired: false });
type Context = ReturnType<typeof initialContext>;
type Effective = { branchVersion: number; campaignVersion: number; effective: Policy; sources: Record<string, string> };
export function CampaignAIBehaviorPolicy({ campaignId, branchId, locale, api }: { campaignId: string; branchId: string; locale: Locale; api: Api }) {
  const t = translate(locale), [behavior, setBehavior] = useState<Effective | null>(null), [context, setContext] = useState(initialContext), [preview, setPreview] = useState<Record<string, unknown> | null>(null), [busy, setBusy] = useState(true), [error, setError] = useState('');
  const sequence = useRef(0);
  async function reload() { const n = ++sequence.current; setBusy(true); setError(''); try { const p = await api<{ behavior: Effective }>('/api/ai/campaigns/' + campaignId + '/effective-configuration'); if (n === sequence.current) { setBehavior(p.behavior); setPreview(null); } } catch (e) { if (n === sequence.current) setError(String(e)); } finally { if (n === sequence.current) setBusy(false); } }
  useEffect(() => { setBehavior(null); void reload(); return () => { ++sequence.current; }; }, [campaignId]);
  const select = (key: 'leadLifecycle' | 'controllerType' | 'conversationState' | 'resolution' | 'trigger', word: keyof typeof words, options: string[]) => <label key={key}>{t(word)}<select aria-label={t(word)} value={context[key]} onChange={e => setContext({ ...context, [key]: e.target.value })}>{options.map(v => <option key={v}>{v}</option>)}</select></label>;
  const check = (key: 'explicitCampaignReference' | 'requiredLeadData' | 'disclosureAlreadySent' | 'humanAvailable' | 'qualificationHandoffRequired', word: keyof typeof words) => <label className="check-row" key={key}><input aria-label={t(word)} type="checkbox" checked={context[key]} onChange={e => setContext({ ...context, [key]: e.target.checked })} />{t(word)}</label>;
  return <section className="panel campaign-ai-configuration" data-campaign-ai-behavior><h3>{t('title')}</h3><p>{t('note')}</p><p>{t('guard')}</p>
    <Editor key={'behavior-branch-' + branchId} scope="BRANCH" id={branchId} locale={locale} api={api} onChanged={reload} />
    <Editor key={'behavior-campaign-' + campaignId} scope="CAMPAIGN" id={campaignId} locale={locale} api={api} onChanged={reload} />
    <button disabled={busy} onClick={() => void reload()}>{t('refresh')}</button>{error && <p role="alert" className="error">{error}</p>}
    {behavior && <div data-ai-behavior-effective><h4>{t('effective')}</h4><p>{t('branch')} · {behavior.branchVersion} / {t('campaign')} · {behavior.campaignVersion}</p><pre className="knowledge-content">{JSON.stringify({ policy: behavior.effective, source: behavior.sources }, null, 2)}</pre></div>}
    <h4>{t('simulation')}</h4><fieldset className="workflow-form" disabled={busy || !behavior}>
      {select('leadLifecycle', 'lifecycle', ['OPEN', 'CLOSED', 'ARCHIVED'])}{select('controllerType', 'controller', ['AI', 'HUMAN', 'NONE'])}{select('conversationState', 'state', ['AI_ACTIVE', 'AI_WAITING_FOR_LEAD', 'AI_HANDOFF_REQUIRED', 'WAITING_FOR_HUMAN', 'HUMAN_ACTIVE', 'CLOSED'])}{select('resolution', 'resolution', ['UNIQUE', 'AMBIGUOUS', 'UNRESOLVED'])}
      {select('trigger', 'trigger', ['NONE', 'CUSTOMER_REQUEST', 'UNKNOWN_ANSWER', 'OUT_OF_SCOPE', 'COMPLAINT', 'SENSITIVE_SCENARIO', 'PRICING_EXCEPTION', 'LEGAL_EXCEPTION', 'PAYMENT_ISSUE', 'LOW_CONFIDENCE', 'MANUAL_TAKEOVER', 'QUALIFICATION', 'REPEATED_MISUNDERSTANDING', 'CAMPAIGN_CONDITION'])}
      <label>{t('count')}<input aria-label={t('count')} type="number" min={0} max={2147483647} step={1} value={context.misunderstandingCount} onChange={e => setContext({ ...context, misunderstandingCount: Number(e.target.value) })} /></label>
      {check('explicitCampaignReference', 'reference')}{check('requiredLeadData', 'required')}{check('disclosureAlreadySent', 'disclosed')}{check('humanAvailable', 'human')}{check('qualificationHandoffRequired', 'qualified')}
      <button onClick={() => { if (!behavior) return; const n = ++sequence.current; setBusy(true); setError(''); void api<Record<string, unknown>>('/api/ai/campaigns/' + campaignId + '/behavior-policy/preview', { method: 'POST', body: JSON.stringify({ branchVersion: behavior.branchVersion, campaignVersion: behavior.campaignVersion, context: context as Context }) }).then(p => { if (n === sequence.current) setPreview(p); }).catch(e => { if (n === sequence.current) setError(String(e)); }).finally(() => { if (n === sequence.current) setBusy(false); }); }}>{t('preview')}</button>
    </fieldset>{preview && <pre className="knowledge-content" data-ai-behavior-preview>{JSON.stringify(preview, null, 2)}</pre>}
  </section>;
}
