import { useEffect,useRef,useState } from 'react';
type Api=<T>(path:string,options?:RequestInit)=>Promise<T>;
type Asset={ id:string;label:string;mime_type:string;size_bytes:number;state:string;version:number;attempt_count:number;error_code:string|null;decision:string|null;approval_reason:string|null;scanner_version:string|null;extracted_text?:string|null };
const words={ title:['ملفات المعرفة المعتمدة','Approved knowledge files','Fichiers de connaissances approuvés'],note:['TXT نص UTF-8 حتى 32KB؛ PDF وPNG/JPEG حتى الحد المعروض. الملفات تُفحص ثم تُراجع صراحة. رفعها أو نجاح الفحص لا ينشرها. النص بيانات غير موثوقة؛ الملفات الثنائية مراجع دون OCR تلقائي.',
  'UTF-8 TXT up to 32KB; PDF and PNG/JPEG up to the displayed limit. Files are scanned then explicitly reviewed. Upload or a clean scan does not publish them. Text is untrusted data; binary files are references without automatic OCR.',
  'TXT UTF-8 jusqu’à 32KB; PDF et PNG/JPEG selon la limite affichée. Analyse puis validation explicite. Le téléversement et l’analyse ne publient rien. Texte non fiable; fichiers binaires sans OCR automatique.'],
  label:['عنوان ملف المعرفة','Knowledge file label','Libellé du fichier'],file:['ملف المعرفة','Knowledge file','Fichier de connaissances'],upload:['رفع ملف المعرفة','Upload knowledge file','Téléverser le fichier'],refresh:['تحديث ملفات المعرفة','Refresh knowledge files','Actualiser les fichiers'],view:['مراجعة ملف المعرفة','Review knowledge file','Examiner le fichier'],download:['تنزيل ملف المعرفة الآمن','Download safe knowledge file','Télécharger le fichier sûr'],reason:['سبب اعتماد أو رفض الملف','Knowledge file review reason','Motif de validation ou rejet'],approve:['اعتماد ملف المعرفة','Approve knowledge file','Approuver le fichier'],reject:['رفض ملف المعرفة','Reject knowledge file','Rejeter le fichier'],include:['إدراج في Knowledge Draft','Include in knowledge draft','Inclure dans le brouillon'],history:['تاريخ فحص الملف','File processing history','Historique du traitement'],more:['المزيد من ملفات المعرفة','More knowledge files','Plus de fichiers'],moreHistory:['المزيد من تاريخ الملف','More file history','Plus d’historique'],binary:['راجع الملف الذي تم تنزيله قبل الاعتماد. لا يوجد نص مستخرج من هذا النوع.', 'Review the downloaded file before approval. This format has no extracted text.','Examinez le fichier téléchargé avant approbation. Aucun texte extrait pour ce format.'] } as const;
export function CampaignKnowledgeAssets({ campaignId,locale,api,selected,onChange,disabled }:{ campaignId:string;locale:'ar'|'en'|'fr';api:Api;selected:string[];onChange:(ids:string[])=>void;disabled:boolean }) {
  const t=(key:keyof typeof words)=>words[key][locale==='ar' ? 0 : locale==='en' ? 1 : 2],root='/api/ai/campaigns/'+campaignId+'/knowledge/assets';
  const [rows,setRows]=useState<Asset[]>([]),[next,setNext]=useState<string|null>(null),[max,setMax]=useState(0),[label,setLabel]=useState(''),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[viewed,setViewed]=useState<Asset|null>(null),[reason,setReason]=useState('');
  const [history,setHistory]=useState<{ version:number;state:string;attempt:string;error_code:string|null }[]>([]),[before,setBefore]=useState<number|null>(null),input=useRef<HTMLInputElement>(null),uploadKey=useRef(crypto.randomUUID());
  async function load(after:string|null=null) { const p=await api<{ items:Asset[];nextId:string|null;maxBytes:number }>(root+(after ? '?after='+after : ''));setRows((old)=>after ? [...old,...p.items] : p.items);setNext(p.nextId);setMax(p.maxBytes); }
  async function run(fn:()=>Promise<void>) { setBusy(true);setError('');try { await fn(); }catch(e){ setError((e as Error).message); }finally { setBusy(false); } }
  async function histories(id:string,b:number|null=null) { const p=await api<{ items:typeof history;nextVersion:number|null }>(root+'/'+id+'/history'+(b ? '?before='+b : ''));setHistory((h)=>b ? [...h,...p.items] : p.items);setBefore(p.nextVersion); }
  async function view(id:string) { setViewed(await api<Asset>(root+'/'+id));setReason('');await histories(id); }
  useEffect(()=>{ setViewed(null);setFile(null);setLabel('');void run(()=>load()); },[campaignId,api]);
  return <section data-knowledge-assets><h4>{t('title')}</h4><p>{t('note')}</p><p>{max} bytes</p>{error && <p role="alert">{error}</p>}
    <div className="knowledge-entry"><label>{t('label')}<input aria-label={t('label')} maxLength={200} disabled={busy || disabled} value={label} onChange={(e)=>{ setLabel(e.target.value);uploadKey.current=crypto.randomUUID(); }} /></label>
      <label>{t('file')}<input ref={input} aria-label={t('file')} type="file" accept=".txt,.pdf,.png,.jpg,.jpeg" disabled={busy || disabled} onChange={(e)=>{ setFile(e.target.files?.[0] ?? null);uploadKey.current=crypto.randomUUID(); }} /></label>
      <button type="button" disabled={busy || disabled || !file || !label.trim()} onClick={()=>void run(async()=> {
        const ext=file!.name.split('.').pop()?.toLowerCase(),mime=({ txt:'text/plain',pdf:'application/pdf',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg' } as Record<string,string>)[ext ?? ''];
        if(!mime || file!.size>max || mime==='text/plain' && file!.size>32768)throw new Error('KNOWLEDGE_ASSET_SIZE_OR_TYPE_INVALID');
        await api(root+'?'+new URLSearchParams({ label,mime,key:uploadKey.current }),{ method:'POST',headers:{ 'Content-Type':'application/octet-stream' },body:file });setFile(null);if(input.current)input.current.value='';uploadKey.current=crypto.randomUUID();await load();
      })}>{t('upload')}</button></div>
    <button type="button" disabled={busy} onClick={()=>void run(async()=>{ await load();if(viewed)await view(viewed.id); })}>{t('refresh')}</button>
    <ul>{rows.map((a)=><li key={a.id} data-knowledge-asset={a.id}><strong>{a.label}</strong> · {a.mime_type} · {a.size_bytes} bytes · {a.decision ?? a.state} · {a.error_code}
      <button type="button" disabled={busy} onClick={()=>void run(()=>view(a.id))}>{t('view')}</button>
      {(a.decision==='APPROVED' || selected.includes(a.id)) && <label><input type="checkbox" aria-label={t('include')+' '+a.label} disabled={busy || disabled || !selected.includes(a.id) && selected.length>=10} checked={selected.includes(a.id)} onChange={(e)=>onChange(e.target.checked ? [...selected,a.id] : selected.filter((id)=>id!==a.id))} />{t('include')}</label>}
    </li>)}</ul>{next && <button type="button" disabled={busy} onClick={()=>void run(()=>load(next))}>{t('more')}</button>}
    {viewed && <section data-knowledge-asset-review><h4>{viewed.label}</h4><p>{viewed.decision ?? viewed.state} · {viewed.scanner_version} · {viewed.error_code}</p>{viewed.extracted_text ? <pre className="knowledge-content">{viewed.extracted_text}</pre> : <p>{t('binary')}</p>}
      {viewed.state==='REVIEW' && viewed.decision!=='REJECTED' && <a href={root+'/'+viewed.id+'/download'} download>{t('download')}</a>}
      {viewed.state==='REVIEW' && !viewed.decision && <><label>{t('reason')}<input aria-label={t('reason')} maxLength={500} disabled={busy || disabled} value={reason} onChange={(e)=>setReason(e.target.value)} /></label>{(['APPROVED','REJECTED'] as const).map((decision)=><button key={decision} type="button" disabled={busy || disabled || reason.trim().length<3} onClick={()=>void run(async()=>{ await api(root+'/'+viewed.id+'/review',{ method:'POST',body:JSON.stringify({ decision,version:viewed.version,reason }) });await load();await view(viewed.id); })}>{t(decision==='APPROVED' ? 'approve' : 'reject')}</button>)}</>}
      <p>{viewed.approval_reason}</p><h5>{t('history')}</h5><ul>{history.map((h)=><li key={h.version}>{h.version} · {h.state} · {h.attempt} · {h.error_code}</li>)}</ul>{before && <button type="button" disabled={busy} onClick={()=>void run(()=>histories(viewed.id,before))}>{t('moreHistory')}</button>}
    </section>}
  </section>;
}
