import { useEffect,useRef,useState } from 'react';
type Api=<T>(path:string,options?:RequestInit)=>Promise<T>;
type Locale='ar'|'en'|'fr';
type Source={ hash:string;providerInvoked:false;executionAvailable:boolean;executionBlocker:string|null;source:{ conversationVersion:number;leadVersion:number;leadOwnerId:string|null;controller:string;messageCount:number;confirmedPaymentCount:number;enrollmentCount:number;truncated:boolean;references:{ id:string;text:string }[] } };
type Summary={ id:string;state:string;error_code:string|null;generatedAt:string|null;stale:boolean;knowledgeVersion:number|null;sourceTruncated:boolean;sensitiveExcerptsOmitted:number;facts:{ messageCount:number;confirmedPaymentCount:number;enrollmentCount:number };result:{ decision:string;references:{ id:string;text:string }[] }|null };
type History={ items:{ id:string;state:string }[];nextBefore:string|null;executionAvailable:boolean };
const summaryStrings={
  en:{ title:'Human Copilot summary',generate:'Generate conversation summary',refresh:'Refresh summary and sources',note:'Derived evidence selection for the employee. No customer send or data edit. Attributed statements do not prove payment. Conversation history remains the source.',disabled:'Live AI data transfer is disabled pending configuration, approvals and controls.',status:'Status',generated:'Generated at',stale:'This summary is stale. Review current history and generate a new summary.',omitted:'Sensitive excerpts omitted',empty:'No usable evidence was selected. Review conversation history.',history:'Summary history',view:'View summary',more:'More summaries',knowledge:'Published knowledge version',limited:'The summary uses a bounded source window and at most eight excerpts.' },
  ar:{ title:'ملخص Human Copilot',generate:'توليد ملخص المحادثة',refresh:'تحديث الملخص والمصادر',note:'اختيار مشتق لمقتطفات تساعد الموظف، بلا إرسال للعميل أو تعديل بياناته. الأقوال المنسوبة لا تثبت الدفع. سجل المحادثة يبقى المصدر.',disabled:'النقل الحي لبيانات AI معطّل حتى استكمال الإعدادات والموافقات والضوابط.',status:'الحالة',generated:'تاريخ التوليد',stale:'الملخص قديم. راجع السجل الحالي وولّد ملخصًا جديدًا.',omitted:'مقتطفات حساسة مستبعدة',empty:'لم تُختر معرفة قابلة للاستخدام؛ راجع سجل المحادثة.',history:'سجل الملخصات',view:'عرض الملخص',more:'ملخصات إضافية',knowledge:'نسخة المعرفة المنشورة',limited:'الملخص يعتمد نافذة مصدر محدودة وحتى ثمانية مقتطفات.' },
  fr:{ title:'Résumé Human Copilot',generate:'Générer le résumé de conversation',refresh:'Actualiser le résumé et les sources',note:'Sélection dérivée pour l’employé, sans envoi ni modification. Les déclarations attribuées ne prouvent pas le paiement. L’historique reste la source.',disabled:'Le transfert IA réel reste désactivé en attente des réglages, autorisations et contrôles.',status:'État',generated:'Généré le',stale:'Résumé périmé. Consultez l’historique actuel et générez un nouveau résumé.',omitted:'Extraits sensibles exclus',empty:'Aucune preuve exploitable sélectionnée. Consultez l’historique.',history:'Historique des résumés',view:'Afficher le résumé',more:'Autres résumés',knowledge:'Version des connaissances publiées',limited:'Fenêtre source limitée et huit extraits au maximum.' },
} as const;
const strings={
  en:{ title:'AI summary source review',read:'Review summary sources',note:'These are authorized conversation excerpts and platform facts, not an AI-generated summary. This review invokes no AI provider and sends no customer message. Customer/history statements do not prove payment.',version:'Source version',count:'Conversation records',paid:'Trusted confirmed payments',enrolled:'Enrollment records',bounded:'Excerpts are limited to the newest 20 text records, up to 2000 characters each. Use conversation history for the full source.',empty:'No text excerpts available.' },
  ar:{ title:'مراجعة مصادر ملخص AI',read:'مراجعة مصادر الملخص',note:'هذه مقتطفات مصرح بها وحقائق من المنصة؛ ليست ملخصًا مولّدًا. المراجعة لا تستدعي مزوّد AI ولا ترسل رسالة للعميل. أقوال العميل أو سجل المحادثة لا تثبت الدفع.',version:'نسخة المصدر',count:'سجلات المحادثة',paid:'دفعات مؤكدة من مصدر موثوق',enrolled:'سجلات التسجيل',bounded:'المقتطفات محدودة بأحدث 20 سجلًا نصيًا، وحتى 2000 حرف لكل سجل. استخدم سجل المحادثة للمصدر الكامل.',empty:'لا تتوفر مقتطفات نصية.' },
  fr:{ title:'Revue des sources du résumé IA',read:'Examiner les sources du résumé',note:'Extraits autorisés et faits de la plateforme, sans résumé généré. Aucun fournisseur IA ni message client. Les déclarations de conversation ne prouvent pas un paiement.',version:'Version source',count:'Enregistrements de conversation',paid:'Paiements confirmés par une source fiable',enrolled:'Inscriptions',bounded:'Les 20 derniers textes, jusqu’à 2000 caractères chacun. Consultez l’historique pour la source complète.',empty:'Aucun extrait de texte.' },
} as const;
export function ConversationSummarySource({ conversationId,locale,api,humanActive,revision }:{ conversationId:string;locale:Locale;api:Api;humanActive:boolean;revision:string }) {
  const t=strings[locale],[source,setSource]=useState<Source|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),sequence=useRef(0);
  const s=summaryStrings[locale],root='/api/conversations/'+conversationId+'/ai-summaries',[summary,setSummary]=useState<Summary|null>(null),[history,setHistory]=useState<History|null>(null),[runBusy,setRunBusy]=useState(false),epoch=useRef(0),selected=useRef<string|null>(null),requestId=useRef<string|null>(null);
  async function loadHistory(before?:string){ const e=epoch.current,r=await api<History>(root+(before ? '?before='+before : ''));if(e===epoch.current)setHistory(h=>before && h ? { ...r,items:[...h.items,...r.items.filter(i=>!h.items.some(old=>old.id===i.id))] } : r); }
  async function view(id:string){ const e=epoch.current;if(selected.current!==id)setSummary(null);selected.current=id;try { const r=await api<Summary>(root+'/'+id);if(e===epoch.current && selected.current===id)setSummary(r); }catch(err){ if(e===epoch.current && selected.current===id){ setSummary(null);setSource(null);setHistory(null);setError((err as Error).message); } } }
  useEffect(()=>{ sequence.current++;epoch.current++;selected.current=null;requestId.current=null;setSource(null);setSummary(null);setError('');setBusy(false);setRunBusy(false);setHistory(null);void loadHistory().catch(e=>setError((e as Error).message));return()=>{ sequence.current++;epoch.current++; }; },[conversationId]);
  useEffect(()=>{ if(selected.current)void view(selected.current).catch(e=>setError((e as Error).message)); },[revision]);
  useEffect(()=>{ if(!summary || !['QUEUED','RUNNING'].includes(summary.state))return;const id=summary.id,e=epoch.current,start=Date.now();let stopped=false,timer:ReturnType<typeof setTimeout>;
    async function poll(){ try { const r=await api<Summary>(root+'/'+id);if(stopped || e!==epoch.current || selected.current!==id)return;setSummary(r);if(['QUEUED','RUNNING'].includes(r.state) && Date.now()-start<180000)timer=setTimeout(()=>void poll(),1500);else await loadHistory(); }catch(err){ if(!stopped && e===epoch.current && selected.current===id){ setSummary(null);setSource(null);setHistory(null);setError((err as Error).message); } } }
    timer=setTimeout(()=>void poll(),1500);return()=>{ stopped=true;clearTimeout(timer); };
  },[summary?.id,summary?.state,conversationId]);
  async function load(){ const s=++sequence.current;setBusy(true);setError('');setSource(null);try { const r=await api<Source>('/api/conversations/'+conversationId+'/ai-summary-context');if(s===sequence.current)setSource(r); }catch(e){ if(s===sequence.current)setError((e as Error).message); }finally { if(s===sequence.current)setBusy(false); } }
  async function refresh(){ await load();await loadHistory();if(selected.current)await view(selected.current); }
  async function generate(){ const e=epoch.current;setRunBusy(true);setError('');requestId.current ??=crypto.randomUUID();try { const r=await api<{ id:string }>(root,{ method:'POST',body:JSON.stringify({ requestId:requestId.current }) });if(e!==epoch.current)return;requestId.current=null;await view(r.id);await loadHistory(); }catch(err){ if(e===epoch.current)setError((err as Error).message); }finally { if(e===epoch.current)setRunBusy(false); } }
  return <section className="panel" data-conversation-summary-source><h4>{t.title}</h4><p>{t.note}</p><button disabled={busy} onClick={()=>void load()}>{t.read}</button>{error && <p role="alert">{error}</p>}
    {source && <div data-summary-source-result><p>{t.version}: {source.source.conversationVersion} · Lead: {source.source.leadVersion}</p><p>{t.count}: {source.source.messageCount}</p><p>{t.paid}: {source.source.confirmedPaymentCount} · {t.enrolled}: {source.source.enrollmentCount}</p>
      {source.source.truncated && <p>{t.bounded}</p>}{!source.source.references.length && <p>{t.empty}</p>}<ul>{source.source.references.map(r=><li key={r.id}><div className="knowledge-content" dir="auto">{r.text}</div></li>)}</ul>
    </div>}
    <section data-copilot-summary><h4>{s.title}</h4><p>{s.note}</p><p>{s.limited}</p>{history?.executionAvailable===false && <p>{s.disabled}</p>}
      <button disabled={busy || runBusy || !humanActive || !source?.executionAvailable} onClick={()=>void generate()}>{s.generate}</button>
      <button className="secondary" disabled={busy || runBusy} onClick={()=>void refresh().catch(e=>setError((e as Error).message))}>{s.refresh}</button>
      {summary && <div data-copilot-summary-result><p>{s.status}: {summary.state}</p>{summary.error_code && <p role="alert">{summary.error_code}</p>}
        {summary.generatedAt && <p>{s.generated}: <time dateTime={summary.generatedAt}>{new Date(summary.generatedAt).toLocaleString(locale)}</time></p>}{summary.stale && <p role="status">{s.stale}</p>}
        <p>{s.knowledge}: {summary.knowledgeVersion ?? '—'}</p><p>{t.paid}: {summary.facts.confirmedPaymentCount} · {t.enrolled}: {summary.facts.enrollmentCount}</p>
        {summary.sourceTruncated && <p>{t.bounded}</p>}{summary.sensitiveExcerptsOmitted>0 && <p>{s.omitted}: {summary.sensitiveExcerptsOmitted}</p>}
        {summary.result && <>{summary.result.decision==='HANDOFF' && <p>{s.empty}</p>}<ul>{summary.result.references.map(r=><li key={r.id}><div className="knowledge-content" dir="auto">{r.text}</div></li>)}</ul></>}
      </div>}
      <h5>{s.history}</h5><ul>{history?.items.map(i=><li key={i.id}>{i.state} <button className="secondary" onClick={()=>void view(i.id).catch(e=>setError((e as Error).message))}>{s.view} {i.id}</button></li>)}</ul>
      {history?.nextBefore && <button disabled={busy || runBusy} onClick={()=>void loadHistory(history.nextBefore!).catch(e=>setError((e as Error).message))}>{s.more}</button>}
    </section>
  </section>;
}
