import { useEffect,useRef,useState } from 'react';
type Api=<T>(path:string,options?:RequestInit)=>Promise<T>;
type Locale='ar'|'en'|'fr';
type Knowledge={ version:number;publishedAt:string;content:{ sections:Record<string,string>;faqs:{ question:string;answer:string }[];allowedClaims:string[];prohibitedClaims:string[];links:{ label:string;url:string }[] };assets:{ id:string;label:string;mimeType:string;sizeBytes:number;extractedText:string|null }[] };
const strings={
  en:{ title:'Published campaign knowledge',read:'Show campaign knowledge',note:'Current approved knowledge for this Lead’s campaign. No draft or other campaign content, AI provider call, automatic customer send or data edit. Links are not fetched automatically.',version:'Published version',date:'Published at',faq:'FAQs',allowed:'Allowed claims',prohibited:'Prohibited claims',links:'Approved links',assets:'Approved files',download:'Download approved file',sections:{ description:'Description',product:'Product and service',prices:'Prices',locations:'Locations',schedules:'Schedules',availability:'Availability',requirements:'Requirements',registration:'Registration',policies:'Policies' } },
  ar:{ title:'معرفة الحملة المنشورة',read:'عرض معرفة الحملة',note:'المعلومات والملفات المنشورة المعتمدة لحملة Lead الحالية. هذه قراءة للموظف؛ لا تُرسل رسالة للعميل. افتح الرابط صراحة لزيارة موقعه.',version:'النسخة المنشورة',date:'تاريخ النشر',faq:'الأسئلة الشائعة',allowed:'الادعاءات المسموحة',prohibited:'الادعاءات المحظورة',links:'الروابط المعتمدة',assets:'الملفات المعتمدة',download:'تحميل الملف المعتمد',sections:{ description:'الوصف',product:'المنتج والخدمة',prices:'الأسعار',locations:'المواقع',schedules:'المواعيد',availability:'التوفر',requirements:'المتطلبات',registration:'التسجيل',policies:'السياسات' } },
  fr:{ title:'Connaissances de campagne publiées',read:'Afficher les connaissances de campagne',note:'Connaissances approuvées de la campagne du Lead. Aucun brouillon, autre campagne, fournisseur IA, envoi automatique ou modification. Les liens ne sont pas consultés automatiquement.',version:'Version publiée',date:'Publié le',faq:'FAQ',allowed:'Affirmations autorisées',prohibited:'Affirmations interdites',links:'Liens approuvés',assets:'Fichiers approuvés',download:'Télécharger le fichier approuvé',sections:{ description:'Description',product:'Produit et service',prices:'Prix',locations:'Lieux',schedules:'Horaires',availability:'Disponibilité',requirements:'Exigences',registration:'Inscription',policies:'Politiques' } },
} as const;
export function ConversationCampaignKnowledge({ conversationId,locale,api,humanActive }:{ conversationId:string;locale:Locale;api:Api;humanActive:boolean }) {
  const t=strings[locale],[value,setValue]=useState<Knowledge|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),sequence=useRef(0),root='/api/conversations/'+conversationId+'/ai-campaign-knowledge';
  useEffect(()=>{ sequence.current++;setValue(null);setError('');setBusy(false);return()=>{ sequence.current++; }; },[conversationId,humanActive]);
  async function load(){ const s=++sequence.current;setBusy(true);setValue(null);setError('');try { const r=await api<Knowledge>(root);if(sequence.current===s)setValue(r); }catch(e){ if(sequence.current===s)setError((e as Error).message); }finally { if(sequence.current===s)setBusy(false); } }
  async function download(a:Knowledge['assets'][number]){ if(!value)return;const s=++sequence.current,version=value.version;setBusy(true);setError('');try {
    const response=await fetch(root+'/assets/'+a.id+'/download?version='+version,{ credentials:'same-origin' });if(!response.ok){ const body=await response.json().catch(()=>null) as { error?:string }|null;throw new Error(body?.error ?? 'KNOWLEDGE_DOWNLOAD_FAILED'); }
    const bytes=await response.blob();if(sequence.current!==s)return;const objectUrl=URL.createObjectURL(bytes),link=document.createElement('a');link.href=objectUrl;link.download='knowledge-'+a.id+'.'+({ 'text/plain':'txt','application/pdf':'pdf','image/png':'png','image/jpeg':'jpg' } as Record<string,string>)[a.mimeType];document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(objectUrl),1000);
  }catch(e){ if(sequence.current===s){ setValue(null);setError((e as Error).message); } }finally { if(sequence.current===s)setBusy(false); } }
  return <section className="panel" data-copilot-knowledge><h4>{t.title}</h4><p>{t.note}</p><button disabled={busy || !humanActive} onClick={()=>void load()}>{t.read}</button>{error && <p role="alert">{error}</p>}
    {value && <div data-copilot-knowledge-result><p>{t.version}: {value.version} · {t.date}: <time dateTime={value.publishedAt}>{new Date(value.publishedAt).toLocaleString(locale)}</time></p>
      {Object.entries(value.content.sections).filter(([,v])=>v).map(([k,v])=><div key={k}><h5>{t.sections[k as keyof typeof t.sections]}</h5><div className="knowledge-content" dir="auto">{v}</div></div>)}
      {!!value.content.faqs.length && <><h5>{t.faq}</h5><ul>{value.content.faqs.map((f,i)=><li key={i}><strong>{f.question}</strong><div className="knowledge-content" dir="auto">{f.answer}</div></li>)}</ul></>}
      {(['allowedClaims','prohibitedClaims'] as const).map(k=>!!value.content[k].length && <div key={k}><h5>{k==='allowedClaims' ? t.allowed : t.prohibited}</h5><ul>{value.content[k].map((v,i)=><li key={i}><div className="knowledge-content" dir="auto">{v}</div></li>)}</ul></div>)}
      {!!value.content.links.length && <><h5>{t.links}</h5><ul>{value.content.links.map((l,i)=><li key={i}><a href={l.url} target="_blank" rel="noopener noreferrer" referrerPolicy="no-referrer">{l.label}</a></li>)}</ul></>}
      {!!value.assets.length && <><h5>{t.assets}</h5><ul>{value.assets.map(a=><li key={a.id}><strong>{a.label}</strong><p>{a.mimeType} · {a.sizeBytes} B</p>{a.extractedText && <div className="knowledge-content" dir="auto">{a.extractedText}</div>}<button className="secondary" disabled={busy} onClick={()=>void download(a)}>{t.download}: {a.label}</button></li>)}</ul></>}
    </div>}
  </section>;
}
