export class PaymentProviderError extends Error {
  constructor(public code:'PAYMENT_PROVIDER_AUTH_FAILED'|'PAYMENT_PROVIDER_RATE_LIMITED'|'PAYMENT_PROVIDER_UNAVAILABLE'
    |'PAYMENT_PROVIDER_RESPONSE_INVALID'|'PAYMENT_MODE_MISMATCH'|'PAYMENT_PROVIDER_OPTIONS_UNSUPPORTED'|'PAYMENT_WEBHOOK_UNSUPPORTED'
    |'PAYMENT_WEBHOOK_ENDPOINT_MISMATCH'|'PAYMENT_WEBHOOK_EVENTS_MISSING'|'PAYMENT_WEBHOOK_ENDPOINT_DISABLED') { super(code); }
}

export class PaymentCheckoutError extends Error {
  constructor(public code:'PAYMENT_PROVIDER_AUTH_FAILED'|'PAYMENT_PROVIDER_RATE_LIMITED'|'PAYMENT_PROVIDER_UNAVAILABLE'|'PAYMENT_PROVIDER_RESPONSE_INVALID'
    |'PAYMENT_PROVIDER_REJECTED'|'PAYMENT_IDEMPOTENCY_CONFLICT'|'PAYMENT_ACCOUNT_MISMATCH'|'PAYMENT_ACCOUNT_NOT_READY'|'PAYMENT_SESSION_MISMATCH'
    |'PAYMENT_APPROVAL_REQUIRED'|'PAYMENT_CAPTURE_MISMATCH',
    public certainty:'REJECTED'|'RETRYABLE'|'UNKNOWN',public retryAfterSeconds:number|null=null) { super(code); }
}
