export class PaymentProviderError extends Error {
  constructor(public code:'PAYMENT_PROVIDER_AUTH_FAILED'|'PAYMENT_PROVIDER_RATE_LIMITED'|'PAYMENT_PROVIDER_UNAVAILABLE'
    |'PAYMENT_PROVIDER_RESPONSE_INVALID'|'PAYMENT_MODE_MISMATCH'|'PAYMENT_PROVIDER_OPTIONS_UNSUPPORTED'|'PAYMENT_WEBHOOK_UNSUPPORTED'
    |'PAYMENT_WEBHOOK_ENDPOINT_MISMATCH'|'PAYMENT_WEBHOOK_EVENTS_MISSING'|'PAYMENT_WEBHOOK_ENDPOINT_DISABLED') { super(code); }
}
